/*
 * Created on 2 Jun 2016 ( Time 17:03:56 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package vnp.dao;

import vnp.bean.IsdnCode;

/**
 * IsdnCode DAO interface
 * 
 * @author Telosys Tools
 */
public interface IsdnCodeDAO {

	// ----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key
	 * 
	 * @param isdn
	 * @param promCode
	 * @return the bean found or null if not found
	 */
	public IsdnCode find(String isdn, long promCode);

	public IsdnCode findByISDN(String isdn);

	// ----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s)
	 * in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from
	 * the database<br>
	 * If not found, the given instance remains unchanged
	 * 
	 * @param isdnCode
	 * @return true if found, false if not found
	 */
	public boolean load(IsdnCode isdnCode);

	public boolean Reward(String isdn, long prizeId, String mtContent, long moId);

	// ----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database
	 * 
	 * @param isdnCode
	 */
	public void insert(IsdnCode isdnCode);

	// ----------------------------------------------------------------------
	/**
	 * Updates the given bean in the database
	 * 
	 * @param isdnCode
	 * @return
	 */
	public int update(IsdnCode isdnCode);

	// ----------------------------------------------------------------------
	/**
	 * Deletes the record in the database using the given primary key value(s)
	 * 
	 * @param isdn
	 * @param promCode
	 * @return
	 */
	public int delete(String isdn, long promCode);

	// ----------------------------------------------------------------------
	/**
	 * Deletes the given bean in the database
	 * 
	 * @param isdnCode
	 * @return
	 */
	public int delete(IsdnCode isdnCode);

	// ----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary
	 * key value(s)
	 * 
	 * @param isdn
	 * @param promCode
	 * @return
	 */
	public boolean exists(String isdn, long promCode);

	// ----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database
	 * 
	 * @param isdnCode
	 * @return
	 */
	public boolean exists(IsdnCode isdnCode);

	// ----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database table
	 * 
	 * @return
	 */
	public long count();

	public long count(String isdn);

}
