/*
 * Created on 20 Jul 2016 ( Time 23:23:24 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package vnp.dao;

import vnp.bean.Maduthuong;

/**
 * Maduthuong DAO interface
 * 
 * @author Telosys Tools
 */
public interface MaduthuongDAO {

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @return the bean found or null if not found 
	 */
	public Maduthuong find(  ) ;

	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param maduthuong
	 * @return true if found, false if not found
	 */
	public boolean load( Maduthuong maduthuong ) ;
	
    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param maduthuong
	 */
	public void insert(Maduthuong maduthuong) ;

    //----------------------------------------------------------------------
	/**
	 * Updates the given bean in the database 
	 * @param maduthuong
	 * @return
	 */
	public int update(Maduthuong maduthuong) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the record in the database using the given primary key value(s) 
	 * @return
	 */
	public int delete(  ) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the given bean in the database 
	 * @param maduthuong
	 * @return
	 */
	public int delete( Maduthuong maduthuong ) ;

    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @return
	 */
	public boolean exists(  ) ;

	//----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param maduthuong
	 * @return
	 */
	public boolean exists( Maduthuong maduthuong ) ;

    //----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database table
	 * @return
	 */
	public long count() ;

}
