/*
 * Created on 17 Jun 2016 ( Time 12:37:08 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package vnp.dao;

import vnp.bean.PostpaidLog;

/**
 * PostpaidLog DAO interface
 * 
 * @author Telosys Tools
 */
public interface PostpaidLogDAO {

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @return the bean found or null if not found 
	 */
	public PostpaidLog find(  ) ;

	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param postpaidLog
	 * @return true if found, false if not found
	 */
	public boolean load( PostpaidLog postpaidLog ) ;
	
    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param postpaidLog
	 */
	public void insert(PostpaidLog postpaidLog) ;

    //----------------------------------------------------------------------
	/**
	 * Updates the given bean in the database 
	 * @param postpaidLog
	 * @return
	 */
	public int update(PostpaidLog postpaidLog) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the record in the database using the given primary key value(s) 
	 * @return
	 */
	public int delete(  ) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the given bean in the database 
	 * @param postpaidLog
	 * @return
	 */
	public int delete( PostpaidLog postpaidLog ) ;

    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @return
	 */
	public boolean exists(  ) ;

	//----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param postpaidLog
	 * @return
	 */
	public boolean exists( PostpaidLog postpaidLog ) ;

    //----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database table
	 * @return
	 */
	public long count() ;

}
