/*
 * Created on 7 Jun 2016 ( Time 13:19:55 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package vnp.dao;

import vnp.bean.PrizeRewardLog;

/**
 * PrizeRewardLog DAO interface
 * 
 * @author Telosys Tools
 */
public interface PrizeRewardLogDAO {

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @return the bean found or null if not found 
	 */
	public PrizeRewardLog find(  ) ;

	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param prizeRewardLog
	 * @return true if found, false if not found
	 */
	public boolean load( PrizeRewardLog prizeRewardLog ) ;
	
    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param prizeRewardLog
	 */
	public void insert(PrizeRewardLog prizeRewardLog) ;

    //----------------------------------------------------------------------
	/**
	 * Updates the given bean in the database 
	 * @param prizeRewardLog
	 * @return
	 */
	public int update(PrizeRewardLog prizeRewardLog) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the record in the database using the given primary key value(s) 
	 * @return
	 */
	public int delete(  ) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the given bean in the database 
	 * @param prizeRewardLog
	 * @return
	 */
	public int delete( PrizeRewardLog prizeRewardLog ) ;

    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @return
	 */
	public boolean exists(  ) ;

	//----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param prizeRewardLog
	 * @return
	 */
	public boolean exists( PrizeRewardLog prizeRewardLog ) ;

    //----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database table
	 * @return
	 */
	public long count() ;

}
