/*
 * Created on 7 Jun 2016 ( Time 10:15:42 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package vnp.dao;

import java.util.List;

import vnp.bean.PrizeReward;

/**
 * PrizeReward DAO interface
 * 
 * @author Telosys Tools
 */
public interface PrizeRewardDAO {

	// ----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key
	 * 
	 * @return the bean found or null if not found
	 */
	public PrizeReward find();

	// ----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s)
	 * in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from
	 * the database<br>
	 * If not found, the given instance remains unchanged
	 * 
	 * @param prizeReward
	 * @return true if found, false if not found
	 */
	public boolean load(PrizeReward prizeReward);

	public List<PrizeReward> SelectPending();

	// ----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database
	 * 
	 * @param prizeReward
	 */
	public void insert(PrizeReward prizeReward);

	// ----------------------------------------------------------------------
	/**
	 * Updates the given bean in the database
	 * 
	 * @param prizeReward
	 * @return
	 */
	public int update(PrizeReward prizeReward);

	// ----------------------------------------------------------------------
	/**
	 * Deletes the record in the database using the given primary key value(s)
	 * 
	 * @return
	 */
	public int delete();

	// ----------------------------------------------------------------------
	/**
	 * Deletes the given bean in the database
	 * 
	 * @param prizeReward
	 * @return
	 */
	public int delete(PrizeReward prizeReward);

	// ----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary
	 * key value(s)
	 * 
	 * @return
	 */
	public boolean exists();

	// ----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database
	 * 
	 * @param prizeReward
	 * @return
	 */
	public boolean exists(PrizeReward prizeReward);

	// ----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database table
	 * 
	 * @return
	 */
	public long count();

}
