/*
 * Created on 23 Jun 2016 ( Time 14:40:51 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package vnp.dao;

import vnp.bean.PrizeRewardBuffer;

/**
 * PrizeRewardBuffer DAO interface
 * 
 * @author Telosys Tools
 */
public interface PrizeRewardBufferDAO {

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @return the bean found or null if not found 
	 */
	public PrizeRewardBuffer find(  ) ;

	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param prizeRewardBuffer
	 * @return true if found, false if not found
	 */
	public boolean load( PrizeRewardBuffer prizeRewardBuffer ) ;
	
    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param prizeRewardBuffer
	 */
	public void insert(PrizeRewardBuffer prizeRewardBuffer) ;

    //----------------------------------------------------------------------
	/**
	 * Updates the given bean in the database 
	 * @param prizeRewardBuffer
	 * @return
	 */
	public int update(PrizeRewardBuffer prizeRewardBuffer) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the record in the database using the given primary key value(s) 
	 * @return
	 */
	public int delete(  ) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the given bean in the database 
	 * @param prizeRewardBuffer
	 * @return
	 */
	public int delete( PrizeRewardBuffer prizeRewardBuffer ) ;

    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @return
	 */
	public boolean exists(  ) ;

	//----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param prizeRewardBuffer
	 * @return
	 */
	public boolean exists( PrizeRewardBuffer prizeRewardBuffer ) ;

    //----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database table
	 * @return
	 */
	public long count() ;

}
