/*
 * Created on 29 Jul 2016 ( Time 09:20:28 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package vnp.dao;

import java.util.List;

import vnp.bean.PrizeList;

/**
 * PrizeList DAO interface
 * 
 * @author Telosys Tools
 */
public interface PrizeListDAO {

	// ----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key
	 * 
	 * @param id
	 * @return the bean found or null if not found
	 */
	public PrizeList find(Long id);

	public List<PrizeList> findByCampaignId(Long id);

	public List<PrizeList> getAll();

	// ----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s)
	 * in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from
	 * the database<br>
	 * If not found, the given instance remains unchanged
	 * 
	 * @param prizeList
	 * @return true if found, false if not found
	 */
	public boolean load(PrizeList prizeList);

	// ----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database
	 * 
	 * @param prizeList
	 */
	public void insert(PrizeList prizeList);

	// ----------------------------------------------------------------------
	/**
	 * Updates the given bean in the database
	 * 
	 * @param prizeList
	 * @return
	 */
	public int update(PrizeList prizeList);

	// ----------------------------------------------------------------------
	/**
	 * Deletes the record in the database using the given primary key value(s)
	 * 
	 * @param id
	 * @return
	 */
	public int delete(Long id);

	// ----------------------------------------------------------------------
	/**
	 * Deletes the given bean in the database
	 * 
	 * @param prizeList
	 * @return
	 */
	public int delete(PrizeList prizeList);

	// ----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary
	 * key value(s)
	 * 
	 * @param id
	 * @return
	 */
	public boolean exists(Long id);

	// ----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database
	 * 
	 * @param prizeList
	 * @return
	 */
	public boolean exists(PrizeList prizeList);

	// ----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database table
	 * 
	 * @return
	 */
	public long count();

}
