/*
 * Created on 2 Jun 2016 ( Time 17:01:53 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package vnp.dao;

import vnp.bean.QueuePostpaidBroadcast;

/**
 * QueuePostpaidBroadcast DAO interface
 * 
 * @author Telosys Tools
 */
public interface QueuePostpaidBroadcastDAO {

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @return the bean found or null if not found 
	 */
	public QueuePostpaidBroadcast find(  ) ;

	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param queuePostpaidBroadcast
	 * @return true if found, false if not found
	 */
	public boolean load( QueuePostpaidBroadcast queuePostpaidBroadcast ) ;
	
    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param queuePostpaidBroadcast
	 */
	public void insert(QueuePostpaidBroadcast queuePostpaidBroadcast) ;

    //----------------------------------------------------------------------
	/**
	 * Updates the given bean in the database 
	 * @param queuePostpaidBroadcast
	 * @return
	 */
	public int update(QueuePostpaidBroadcast queuePostpaidBroadcast) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the record in the database using the given primary key value(s) 
	 * @return
	 */
	public int delete(  ) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the given bean in the database 
	 * @param queuePostpaidBroadcast
	 * @return
	 */
	public int delete( QueuePostpaidBroadcast queuePostpaidBroadcast ) ;

    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @return
	 */
	public boolean exists(  ) ;

	//----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param queuePostpaidBroadcast
	 * @return
	 */
	public boolean exists( QueuePostpaidBroadcast queuePostpaidBroadcast ) ;

    //----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database table
	 * @return
	 */
	public long count() ;

}
