/*
 * Created on 2 Jun 2016 ( Time 17:03:04 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package vnp.dao;

import vnp.bean.SmsLog;

/**
 * SmsLog DAO interface
 * 
 * @author Telosys Tools
 */
public interface SmsLogDAO {

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @return the bean found or null if not found 
	 */
	public SmsLog find(  ) ;

	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param smsLog
	 * @return true if found, false if not found
	 */
	public boolean load( SmsLog smsLog ) ;
	
    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param smsLog
	 */
	public void insert(SmsLog smsLog) ;

    //----------------------------------------------------------------------
	/**
	 * Updates the given bean in the database 
	 * @param smsLog
	 * @return
	 */
	public int update(SmsLog smsLog) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the record in the database using the given primary key value(s) 
	 * @return
	 */
	public int delete(  ) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the given bean in the database 
	 * @param smsLog
	 * @return
	 */
	public int delete( SmsLog smsLog ) ;

    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @return
	 */
	public boolean exists(  ) ;

	//----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param smsLog
	 * @return
	 */
	public boolean exists( SmsLog smsLog ) ;

    //----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database table
	 * @return
	 */
	public long count() ;

}
