/*
 * Created on 3 Jun 2016 ( Time 16:24:32 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package vnp.dao;

import java.math.BigDecimal;

import vnp.bean.SmsMt;

/**
 * SmsMt DAO interface
 * 
 * @author Telosys Tools
 */
public interface SmsMtDAO {

	// ----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key
	 * 
	 * @param id
	 * @return the bean found or null if not found
	 */
	public SmsMt find(BigDecimal id);

	// ----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s)
	 * in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from
	 * the database<br>
	 * If not found, the given instance remains unchanged
	 * 
	 * @param smsMt
	 * @return true if found, false if not found
	 */
	public boolean load(SmsMt smsMt);

	// ----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database
	 * 
	 * @param smsMt
	 */
	public void insert(SmsMt smsMt);

	// ----------------------------------------------------------------------
	/**
	 * Updates the given bean in the database
	 * 
	 * @param smsMt
	 * @return
	 */
	public int update(SmsMt smsMt);

	// ----------------------------------------------------------------------
	/**
	 * Deletes the record in the database using the given primary key value(s)
	 * 
	 * @param id
	 * @return
	 */
	public int delete(BigDecimal id);

	// ----------------------------------------------------------------------
	/**
	 * Deletes the given bean in the database
	 * 
	 * @param smsMt
	 * @return
	 */
	public int delete(SmsMt smsMt);

	// ----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary
	 * key value(s)
	 * 
	 * @param id
	 * @return
	 */
	public boolean exists(BigDecimal id);

	// ----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database
	 * 
	 * @param smsMt
	 * @return
	 */
	public boolean exists(SmsMt smsMt);

	// ----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database table
	 * 
	 * @return
	 */
	public long count();

}
