/*
 * Created on 3 Jun 2016 ( Time 16:24:32 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package vnp.dao;

import java.util.List;

import vnp.bean.SmsMo;

/**
 * SmsMo DAO interface
 * 
 * @author Telosys Tools
 */
public interface SmsMoDAO {

	// ----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key
	 * 
	 * @param id
	 * @return the bean found or null if not found
	 */
	public SmsMo find(long id);

	public List<SmsMo> getPending();

	// ----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s)
	 * in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from
	 * the database<br>
	 * If not found, the given instance remains unchanged
	 * 
	 * @param smsMo
	 * @return true if found, false if not found
	 */
	public boolean load(SmsMo smsMo);

	public boolean MoResponse(long moId, String isdn, String resContent);

	// ----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database
	 * 
	 * @param smsMo
	 */
	public void insert(SmsMo smsMo);

	// ----------------------------------------------------------------------
	/**
	 * Updates the given bean in the database
	 * 
	 * @param smsMo
	 * @return
	 */
	public int update(SmsMo smsMo);

	// ----------------------------------------------------------------------
	/**
	 * Deletes the record in the database using the given primary key value(s)
	 * 
	 * @param id
	 * @return
	 */
	public int delete(long id);

	// ----------------------------------------------------------------------
	/**
	 * Deletes the given bean in the database
	 * 
	 * @param smsMo
	 * @return
	 */
	public int delete(SmsMo smsMo);

	// ----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary
	 * key value(s)
	 * 
	 * @param id
	 * @return
	 */
	public boolean exists(long id);

	// ----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database
	 * 
	 * @param smsMo
	 * @return
	 */
	public boolean exists(SmsMo smsMo);

	// ----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database table
	 * 
	 * @return
	 */
	public long count();

}
