/*
 * Created on 17 Jun 2016 ( Time 12:35:41 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package vnp.dao;

import vnp.bean.SubInAccumulate;

/**
 * SubInAccumulate DAO interface
 * 
 * @author Telosys Tools
 */
public interface SubInAccumulateDAO {

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @return the bean found or null if not found 
	 */
	public SubInAccumulate find(  ) ;

	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param subInAccumulate
	 * @return true if found, false if not found
	 */
	public boolean load( SubInAccumulate subInAccumulate ) ;
	
    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param subInAccumulate
	 */
	public void insert(SubInAccumulate subInAccumulate) ;

    //----------------------------------------------------------------------
	/**
	 * Updates the given bean in the database 
	 * @param subInAccumulate
	 * @return
	 */
	public int update(SubInAccumulate subInAccumulate) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the record in the database using the given primary key value(s) 
	 * @return
	 */
	public int delete(  ) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the given bean in the database 
	 * @param subInAccumulate
	 * @return
	 */
	public int delete( SubInAccumulate subInAccumulate ) ;

    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @return
	 */
	public boolean exists(  ) ;

	//----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param subInAccumulate
	 * @return
	 */
	public boolean exists( SubInAccumulate subInAccumulate ) ;

    //----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database table
	 * @return
	 */
	public long count() ;

}
