/*
 * Created on 17 Jun 2016 ( Time 12:35:41 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package vnp.dao;

import vnp.bean.SubsInDaily;

/**
 * SubsInDaily DAO interface
 * 
 * @author Telosys Tools
 */
public interface SubsInDailyDAO {

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @return the bean found or null if not found 
	 */
	public SubsInDaily find(  ) ;

	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param subsInDaily
	 * @return true if found, false if not found
	 */
	public boolean load( SubsInDaily subsInDaily ) ;
	
    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param subsInDaily
	 */
	public void insert(SubsInDaily subsInDaily) ;

    //----------------------------------------------------------------------
	/**
	 * Updates the given bean in the database 
	 * @param subsInDaily
	 * @return
	 */
	public int update(SubsInDaily subsInDaily) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the record in the database using the given primary key value(s) 
	 * @return
	 */
	public int delete(  ) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the given bean in the database 
	 * @param subsInDaily
	 * @return
	 */
	public int delete( SubsInDaily subsInDaily ) ;

    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @return
	 */
	public boolean exists(  ) ;

	//----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param subsInDaily
	 * @return
	 */
	public boolean exists( SubsInDaily subsInDaily ) ;

    //----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database table
	 * @return
	 */
	public long count() ;

}
