/*
 * Created on 18 Nov 2016 ( Time 09:26:51 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package vnp.dao;

import vnp.bean.WinMtLog;

/**
 * WinMtLog DAO interface
 * 
 * @author Telosys Tools
 */
public interface WinMtLogDAO {

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @return the bean found or null if not found 
	 */
	public WinMtLog find(  ) ;

	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param winMtLog
	 * @return true if found, false if not found
	 */
	public boolean load( WinMtLog winMtLog ) ;
	
    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param winMtLog
	 */
	public void insert(WinMtLog winMtLog) ;

    //----------------------------------------------------------------------
	/**
	 * Updates the given bean in the database 
	 * @param winMtLog
	 * @return
	 */
	public int update(WinMtLog winMtLog) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the record in the database using the given primary key value(s) 
	 * @return
	 */
	public int delete(  ) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the given bean in the database 
	 * @param winMtLog
	 * @return
	 */
	public int delete( WinMtLog winMtLog ) ;

    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @return
	 */
	public boolean exists(  ) ;

	//----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param winMtLog
	 * @return
	 */
	public boolean exists( WinMtLog winMtLog ) ;

    //----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database table
	 * @return
	 */
	public long count() ;

}
