/*
 * Created on 18 Nov 2016 ( Time 09:26:51 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package vnp.dao;

import vnp.bean.WinPrizes;

/**
 * WinPrizes DAO interface
 * 
 * @author Telosys Tools
 */
public interface WinPrizesDAO {

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @param campaignId
	 * @param prizeLevel
	 * @return the bean found or null if not found 
	 */
	public WinPrizes find( Long campaignId, Long prizeLevel ) ;

	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param winPrizes
	 * @return true if found, false if not found
	 */
	public boolean load( WinPrizes winPrizes ) ;
	
    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param winPrizes
	 */
	public void insert(WinPrizes winPrizes) ;

    //----------------------------------------------------------------------
	/**
	 * Updates the given bean in the database 
	 * @param winPrizes
	 * @return
	 */
	public int update(WinPrizes winPrizes) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the record in the database using the given primary key value(s) 
	 * @param campaignId
	 * @param prizeLevel
	 * @return
	 */
	public int delete( Long campaignId, Long prizeLevel ) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the given bean in the database 
	 * @param winPrizes
	 * @return
	 */
	public int delete( WinPrizes winPrizes ) ;

    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @param campaignId
	 * @param prizeLevel
	 * @return
	 */
	public boolean exists( Long campaignId, Long prizeLevel ) ;

	//----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param winPrizes
	 * @return
	 */
	public boolean exists( WinPrizes winPrizes ) ;

    //----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database table
	 * @return
	 */
	public long count() ;

}
