/*
 * Created on 2 Jun 2016 ( Time 17:03:56 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package vnp.dao.impl.jdbc;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import vnp.bean.IsdnAll;
import vnp.dao.IsdnAllDAO;
import vnp.dao.impl.jdbc.commons.GenericDAO;

/**
 * IsdnAll DAO implementation 
 * 
 * @author Telosys Tools
 *
 */
public class IsdnAllDAOImpl extends GenericDAO<IsdnAll> implements IsdnAllDAO {

	private final static String SQL_SELECT = 
		"select ISDN, NO_CODE, DATE_ACTIVE, DATE_IMPORT, SUBTYPE, SERVICE, PROVINCE, MAIN_CHARGE, GROUP_TYPE, GROUP_CODE, NETWORK, CODE_STATUS, RANGE_INDEX from ISDN_ALL where ";

	private final static String SQL_INSERT = 
		"insert into ISDN_ALL ( ISDN, NO_CODE, DATE_ACTIVE, DATE_IMPORT, SUBTYPE, SERVICE, PROVINCE, MAIN_CHARGE, GROUP_TYPE, GROUP_CODE, NETWORK, CODE_STATUS, RANGE_INDEX ) values ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? )";

	private final static String SQL_UPDATE = 
		"update ISDN_ALL set ISDN = ?, NO_CODE = ?, DATE_ACTIVE = ?, DATE_IMPORT = ?, SUBTYPE = ?, SERVICE = ?, PROVINCE = ?, MAIN_CHARGE = ?, GROUP_TYPE = ?, GROUP_CODE = ?, NETWORK = ?, CODE_STATUS = ?, RANGE_INDEX = ? where ";

	private final static String SQL_DELETE = 
		"delete from ISDN_ALL where ";

	private final static String SQL_COUNT_ALL = 
		"select count(*) from ISDN_ALL";

	private final static String SQL_COUNT = 
		"select count(*) from ISDN_ALL where ";

    //----------------------------------------------------------------------
	/**
	 * DAO constructor
	 */
	public IsdnAllDAOImpl() {
		super();
	}

	//----------------------------------------------------------------------
	/**
	 * Creates a new instance of the bean and populates it with the given primary value(s)
	 * @return the new instance
	 */
	private IsdnAll newInstanceWithPrimaryKey(  ) {
		IsdnAll isdnAll = new IsdnAll();
		return isdnAll ;
	}

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @return the bean found or null if not found 
	 */
	@Override
	public IsdnAll find(  ) {
		IsdnAll isdnAll = newInstanceWithPrimaryKey(  ) ;
		if ( super.doSelect(isdnAll) ) {
			return isdnAll ;
		}
		else {
			return null ; // Not found
		}
	}
	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param isdnAll
	 * @return true if found, false if not found
	 */
	@Override
	public boolean load( IsdnAll isdnAll ) {
		return super.doSelect(isdnAll) ;
	}
    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param isdnAll
	 */
	@Override
	public void insert(IsdnAll isdnAll) {
		super.doInsert(isdnAll);
	}	

    //----------------------------------------------------------------------
	/**
	 * Updates the given bean in the database 
	 * @param isdnAll
	 * @return
	 */
	@Override
	public int update(IsdnAll isdnAll) {
		return super.doUpdate(isdnAll);
	}	

    //----------------------------------------------------------------------
	/**
	 * Deletes the record in the database using the given primary key value(s) 
	 * @return
	 */
	@Override
	public int delete(  ) {
		IsdnAll isdnAll = newInstanceWithPrimaryKey(  ) ;
		return super.doDelete(isdnAll);
	}

    //----------------------------------------------------------------------
	/**
	 * Deletes the given bean in the database 
	 * @param isdnAll
	 * @return
	 */
	@Override
	public int delete( IsdnAll isdnAll ) {
		return super.doDelete(isdnAll);
	}

    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @return
	 */
	@Override
	public boolean exists(  ) {
		IsdnAll isdnAll = newInstanceWithPrimaryKey(  ) ;
		return super.doExists(isdnAll);
	}
    //----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param isdnAll
	 * @return
	 */
	@Override
	public boolean exists( IsdnAll isdnAll ) {
		return super.doExists(isdnAll);
	}

    //----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database
	 * @return
	 */
	@Override
	public long count() {
		return super.doCountAll();
	}

    //----------------------------------------------------------------------
	@Override
	protected String getSqlSelect() {
		return SQL_SELECT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlInsert() {
		return SQL_INSERT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlUpdate() {
		return SQL_UPDATE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlDelete() {
		return SQL_DELETE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCount() {
		return SQL_COUNT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCountAll() {
		return SQL_COUNT_ALL ;
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForPrimaryKey(PreparedStatement ps, int i, IsdnAll isdnAll) throws SQLException {
		//--- Set PRIMARY KEY from bean to PreparedStatement ( SQL "WHERE key=?, ..." )
	}

    //----------------------------------------------------------------------
	@Override
	protected IsdnAll populateBean(ResultSet rs, IsdnAll isdnAll) throws SQLException {

		//--- Set data from ResultSet to Bean attributes
		isdnAll.setIsdn(rs.getString("ISDN")); // java.lang.String
		isdnAll.setNoCode(rs.getBigDecimal("NO_CODE")); // java.math.BigDecimal
		if ( rs.wasNull() ) { isdnAll.setNoCode(null); }; // not primitive number => keep null value if any
		isdnAll.setDateActive(rs.getDate("DATE_ACTIVE")); // java.util.Date
		isdnAll.setDateImport(rs.getDate("DATE_IMPORT")); // java.util.Date
		isdnAll.setSubtype(rs.getString("SUBTYPE")); // java.lang.String
		isdnAll.setService(rs.getString("SERVICE")); // java.lang.String
		isdnAll.setProvince(rs.getString("PROVINCE")); // java.lang.String
		isdnAll.setMainCharge(rs.getBigDecimal("MAIN_CHARGE")); // java.math.BigDecimal
		if ( rs.wasNull() ) { isdnAll.setMainCharge(null); }; // not primitive number => keep null value if any
		isdnAll.setGroupType(rs.getString("GROUP_TYPE")); // java.lang.String
		isdnAll.setGroupCode(rs.getString("GROUP_CODE")); // java.lang.String
		isdnAll.setNetwork(rs.getString("NETWORK")); // java.lang.String
		isdnAll.setCodeStatus(rs.getString("CODE_STATUS")); // java.lang.String
		isdnAll.setRangeIndex(rs.getBigDecimal("RANGE_INDEX")); // java.math.BigDecimal
		if ( rs.wasNull() ) { isdnAll.setRangeIndex(null); }; // not primitive number => keep null value if any
		return isdnAll ;
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForInsert(PreparedStatement ps, int i, IsdnAll isdnAll) throws SQLException {

		//--- Set PRIMARY KEY and DATA from bean to PreparedStatement ( SQL "SET x=?, y=?, ..." )
		setValue(ps, i++, isdnAll.getIsdn() ) ; // "ISDN" : java.lang.String
		setValue(ps, i++, isdnAll.getNoCode() ) ; // "NO_CODE" : java.math.BigDecimal
		setValue(ps, i++, isdnAll.getDateActive() ) ; // "DATE_ACTIVE" : java.util.Date
		setValue(ps, i++, isdnAll.getDateImport() ) ; // "DATE_IMPORT" : java.util.Date
		setValue(ps, i++, isdnAll.getSubtype() ) ; // "SUBTYPE" : java.lang.String
		setValue(ps, i++, isdnAll.getService() ) ; // "SERVICE" : java.lang.String
		setValue(ps, i++, isdnAll.getProvince() ) ; // "PROVINCE" : java.lang.String
		setValue(ps, i++, isdnAll.getMainCharge() ) ; // "MAIN_CHARGE" : java.math.BigDecimal
		setValue(ps, i++, isdnAll.getGroupType() ) ; // "GROUP_TYPE" : java.lang.String
		setValue(ps, i++, isdnAll.getGroupCode() ) ; // "GROUP_CODE" : java.lang.String
		setValue(ps, i++, isdnAll.getNetwork() ) ; // "NETWORK" : java.lang.String
		setValue(ps, i++, isdnAll.getCodeStatus() ) ; // "CODE_STATUS" : java.lang.String
		setValue(ps, i++, isdnAll.getRangeIndex() ) ; // "RANGE_INDEX" : java.math.BigDecimal
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForUpdate(PreparedStatement ps, int i, IsdnAll isdnAll) throws SQLException {

		//--- Set DATA from bean to PreparedStatement ( SQL "SET x=?, y=?, ..." )
		setValue(ps, i++, isdnAll.getIsdn() ) ; // "ISDN" : java.lang.String
		setValue(ps, i++, isdnAll.getNoCode() ) ; // "NO_CODE" : java.math.BigDecimal
		setValue(ps, i++, isdnAll.getDateActive() ) ; // "DATE_ACTIVE" : java.util.Date
		setValue(ps, i++, isdnAll.getDateImport() ) ; // "DATE_IMPORT" : java.util.Date
		setValue(ps, i++, isdnAll.getSubtype() ) ; // "SUBTYPE" : java.lang.String
		setValue(ps, i++, isdnAll.getService() ) ; // "SERVICE" : java.lang.String
		setValue(ps, i++, isdnAll.getProvince() ) ; // "PROVINCE" : java.lang.String
		setValue(ps, i++, isdnAll.getMainCharge() ) ; // "MAIN_CHARGE" : java.math.BigDecimal
		setValue(ps, i++, isdnAll.getGroupType() ) ; // "GROUP_TYPE" : java.lang.String
		setValue(ps, i++, isdnAll.getGroupCode() ) ; // "GROUP_CODE" : java.lang.String
		setValue(ps, i++, isdnAll.getNetwork() ) ; // "NETWORK" : java.lang.String
		setValue(ps, i++, isdnAll.getCodeStatus() ) ; // "CODE_STATUS" : java.lang.String
		setValue(ps, i++, isdnAll.getRangeIndex() ) ; // "RANGE_INDEX" : java.math.BigDecimal
		//--- Set PRIMARY KEY from bean to PreparedStatement ( SQL "WHERE key=?, ..." )
	}

}
