/*
 * Created on 20 Jul 2016 ( Time 23:23:24 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package vnp.dao.impl.jdbc;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import vnp.bean.Maduthuong;
import vnp.dao.MaduthuongDAO;
import vnp.dao.impl.jdbc.commons.GenericDAO;

/**
 * Maduthuong DAO implementation 
 * 
 * @author Telosys Tools
 *
 */
public class MaduthuongDAOImpl extends GenericDAO<Maduthuong> implements MaduthuongDAO {

	private final static String SQL_SELECT = 
		"select ID, MSISDN, MDT, PROVINCE, NOTE, DATETIME, EVT_DTIME, STATUS, EVENTLOGS_SEQ_ID, SUBTYPE from MADUTHUONG where ";

	private final static String SQL_INSERT = 
		"insert into MADUTHUONG ( ID, MSISDN, MDT, PROVINCE, NOTE, DATETIME, EVT_DTIME, STATUS, EVENTLOGS_SEQ_ID, SUBTYPE ) values ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ? )";

	private final static String SQL_UPDATE = 
		"update MADUTHUONG set ID = ?, MSISDN = ?, MDT = ?, PROVINCE = ?, NOTE = ?, DATETIME = ?, EVT_DTIME = ?, STATUS = ?, EVENTLOGS_SEQ_ID = ?, SUBTYPE = ? where ";

	private final static String SQL_DELETE = 
		"delete from MADUTHUONG where ";

	private final static String SQL_COUNT_ALL = 
		"select count(*) from MADUTHUONG";

	private final static String SQL_COUNT = 
		"select count(*) from MADUTHUONG where ";

    //----------------------------------------------------------------------
	/**
	 * DAO constructor
	 */
	public MaduthuongDAOImpl() {
		super();
	}

	//----------------------------------------------------------------------
	/**
	 * Creates a new instance of the bean and populates it with the given primary value(s)
	 * @return the new instance
	 */
	private Maduthuong newInstanceWithPrimaryKey(  ) {
		Maduthuong maduthuong = new Maduthuong();
		return maduthuong ;
	}

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @return the bean found or null if not found 
	 */
	@Override
	public Maduthuong find(  ) {
		Maduthuong maduthuong = newInstanceWithPrimaryKey(  ) ;
		if ( super.doSelect(maduthuong) ) {
			return maduthuong ;
		}
		else {
			return null ; // Not found
		}
	}
	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param maduthuong
	 * @return true if found, false if not found
	 */
	@Override
	public boolean load( Maduthuong maduthuong ) {
		return super.doSelect(maduthuong) ;
	}
    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param maduthuong
	 */
	@Override
	public void insert(Maduthuong maduthuong) {
		super.doInsert(maduthuong);
	}	

    //----------------------------------------------------------------------
	/**
	 * Updates the given bean in the database 
	 * @param maduthuong
	 * @return
	 */
	@Override
	public int update(Maduthuong maduthuong) {
		return super.doUpdate(maduthuong);
	}	

    //----------------------------------------------------------------------
	/**
	 * Deletes the record in the database using the given primary key value(s) 
	 * @return
	 */
	@Override
	public int delete(  ) {
		Maduthuong maduthuong = newInstanceWithPrimaryKey(  ) ;
		return super.doDelete(maduthuong);
	}

    //----------------------------------------------------------------------
	/**
	 * Deletes the given bean in the database 
	 * @param maduthuong
	 * @return
	 */
	@Override
	public int delete( Maduthuong maduthuong ) {
		return super.doDelete(maduthuong);
	}

    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @return
	 */
	@Override
	public boolean exists(  ) {
		Maduthuong maduthuong = newInstanceWithPrimaryKey(  ) ;
		return super.doExists(maduthuong);
	}
    //----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param maduthuong
	 * @return
	 */
	@Override
	public boolean exists( Maduthuong maduthuong ) {
		return super.doExists(maduthuong);
	}

    //----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database
	 * @return
	 */
	@Override
	public long count() {
		return super.doCountAll();
	}

    //----------------------------------------------------------------------
	@Override
	protected String getSqlSelect() {
		return SQL_SELECT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlInsert() {
		return SQL_INSERT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlUpdate() {
		return SQL_UPDATE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlDelete() {
		return SQL_DELETE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCount() {
		return SQL_COUNT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCountAll() {
		return SQL_COUNT_ALL ;
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForPrimaryKey(PreparedStatement ps, int i, Maduthuong maduthuong) throws SQLException {
		//--- Set PRIMARY KEY from bean to PreparedStatement ( SQL "WHERE key=?, ..." )
	}

    //----------------------------------------------------------------------
	@Override
	protected Maduthuong populateBean(ResultSet rs, Maduthuong maduthuong) throws SQLException {

		//--- Set data from ResultSet to Bean attributes
		maduthuong.setId(rs.getLong("ID")); // java.lang.Long
		if ( rs.wasNull() ) { maduthuong.setId(null); }; // not primitive number => keep null value if any
		maduthuong.setMsisdn(rs.getString("MSISDN")); // java.lang.String
		maduthuong.setMdt(rs.getLong("MDT")); // java.lang.Long
		if ( rs.wasNull() ) { maduthuong.setMdt(null); }; // not primitive number => keep null value if any
		maduthuong.setProvince(rs.getString("PROVINCE")); // java.lang.String
		maduthuong.setNote(rs.getString("NOTE")); // java.lang.String
		maduthuong.setDatetime(rs.getDate("DATETIME")); // java.util.Date
		maduthuong.setEvtDtime(rs.getDate("EVT_DTIME")); // java.util.Date
		maduthuong.setStatus(rs.getLong("STATUS")); // java.lang.Long
		if ( rs.wasNull() ) { maduthuong.setStatus(null); }; // not primitive number => keep null value if any
		maduthuong.setEventlogsSeqId(rs.getLong("EVENTLOGS_SEQ_ID")); // java.lang.Long
		if ( rs.wasNull() ) { maduthuong.setEventlogsSeqId(null); }; // not primitive number => keep null value if any
		maduthuong.setSubtype(rs.getString("SUBTYPE")); // java.lang.String
		return maduthuong ;
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForInsert(PreparedStatement ps, int i, Maduthuong maduthuong) throws SQLException {

		//--- Set PRIMARY KEY and DATA from bean to PreparedStatement ( SQL "SET x=?, y=?, ..." )
		setValue(ps, i++, maduthuong.getId() ) ; // "ID" : java.lang.Long
		setValue(ps, i++, maduthuong.getMsisdn() ) ; // "MSISDN" : java.lang.String
		setValue(ps, i++, maduthuong.getMdt() ) ; // "MDT" : java.lang.Long
		setValue(ps, i++, maduthuong.getProvince() ) ; // "PROVINCE" : java.lang.String
		setValue(ps, i++, maduthuong.getNote() ) ; // "NOTE" : java.lang.String
		setValue(ps, i++, maduthuong.getDatetime() ) ; // "DATETIME" : java.util.Date
		setValue(ps, i++, maduthuong.getEvtDtime() ) ; // "EVT_DTIME" : java.util.Date
		setValue(ps, i++, maduthuong.getStatus() ) ; // "STATUS" : java.lang.Long
		setValue(ps, i++, maduthuong.getEventlogsSeqId() ) ; // "EVENTLOGS_SEQ_ID" : java.lang.Long
		setValue(ps, i++, maduthuong.getSubtype() ) ; // "SUBTYPE" : java.lang.String
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForUpdate(PreparedStatement ps, int i, Maduthuong maduthuong) throws SQLException {

		//--- Set DATA from bean to PreparedStatement ( SQL "SET x=?, y=?, ..." )
		setValue(ps, i++, maduthuong.getId() ) ; // "ID" : java.lang.Long
		setValue(ps, i++, maduthuong.getMsisdn() ) ; // "MSISDN" : java.lang.String
		setValue(ps, i++, maduthuong.getMdt() ) ; // "MDT" : java.lang.Long
		setValue(ps, i++, maduthuong.getProvince() ) ; // "PROVINCE" : java.lang.String
		setValue(ps, i++, maduthuong.getNote() ) ; // "NOTE" : java.lang.String
		setValue(ps, i++, maduthuong.getDatetime() ) ; // "DATETIME" : java.util.Date
		setValue(ps, i++, maduthuong.getEvtDtime() ) ; // "EVT_DTIME" : java.util.Date
		setValue(ps, i++, maduthuong.getStatus() ) ; // "STATUS" : java.lang.Long
		setValue(ps, i++, maduthuong.getEventlogsSeqId() ) ; // "EVENTLOGS_SEQ_ID" : java.lang.Long
		setValue(ps, i++, maduthuong.getSubtype() ) ; // "SUBTYPE" : java.lang.String
		//--- Set PRIMARY KEY from bean to PreparedStatement ( SQL "WHERE key=?, ..." )
	}

}
