/*
 * Created on 17 Jun 2016 ( Time 12:37:08 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package vnp.dao.impl.jdbc;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import vnp.bean.PostpaidLog;
import vnp.dao.PostpaidLogDAO;
import vnp.dao.impl.jdbc.commons.GenericDAO;

/**
 * PostpaidLog DAO implementation 
 * 
 * @author Telosys Tools
 *
 */
public class PostpaidLogDAOImpl extends GenericDAO<PostpaidLog> implements PostpaidLogDAO {

	private final static String SQL_SELECT = 
		"select ID, BILL_DATE, LOG_PROCESS, STATUS, NUM_REC from POSTPAID_LOG where ";

	private final static String SQL_INSERT = 
		"insert into POSTPAID_LOG ( ID, BILL_DATE, LOG_PROCESS, STATUS, NUM_REC ) values ( ?, ?, ?, ?, ? )";

	private final static String SQL_UPDATE = 
		"update POSTPAID_LOG set ID = ?, BILL_DATE = ?, LOG_PROCESS = ?, STATUS = ?, NUM_REC = ? where ";

	private final static String SQL_DELETE = 
		"delete from POSTPAID_LOG where ";

	private final static String SQL_COUNT_ALL = 
		"select count(*) from POSTPAID_LOG";

	private final static String SQL_COUNT = 
		"select count(*) from POSTPAID_LOG where ";

    //----------------------------------------------------------------------
	/**
	 * DAO constructor
	 */
	public PostpaidLogDAOImpl() {
		super();
	}

	//----------------------------------------------------------------------
	/**
	 * Creates a new instance of the bean and populates it with the given primary value(s)
	 * @return the new instance
	 */
	private PostpaidLog newInstanceWithPrimaryKey(  ) {
		PostpaidLog postpaidLog = new PostpaidLog();
		return postpaidLog ;
	}

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @return the bean found or null if not found 
	 */
	@Override
	public PostpaidLog find(  ) {
		PostpaidLog postpaidLog = newInstanceWithPrimaryKey(  ) ;
		if ( super.doSelect(postpaidLog) ) {
			return postpaidLog ;
		}
		else {
			return null ; // Not found
		}
	}
	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param postpaidLog
	 * @return true if found, false if not found
	 */
	@Override
	public boolean load( PostpaidLog postpaidLog ) {
		return super.doSelect(postpaidLog) ;
	}
    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param postpaidLog
	 */
	@Override
	public void insert(PostpaidLog postpaidLog) {
		super.doInsert(postpaidLog);
	}	

    //----------------------------------------------------------------------
	/**
	 * Updates the given bean in the database 
	 * @param postpaidLog
	 * @return
	 */
	@Override
	public int update(PostpaidLog postpaidLog) {
		return super.doUpdate(postpaidLog);
	}	

    //----------------------------------------------------------------------
	/**
	 * Deletes the record in the database using the given primary key value(s) 
	 * @return
	 */
	@Override
	public int delete(  ) {
		PostpaidLog postpaidLog = newInstanceWithPrimaryKey(  ) ;
		return super.doDelete(postpaidLog);
	}

    //----------------------------------------------------------------------
	/**
	 * Deletes the given bean in the database 
	 * @param postpaidLog
	 * @return
	 */
	@Override
	public int delete( PostpaidLog postpaidLog ) {
		return super.doDelete(postpaidLog);
	}

    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @return
	 */
	@Override
	public boolean exists(  ) {
		PostpaidLog postpaidLog = newInstanceWithPrimaryKey(  ) ;
		return super.doExists(postpaidLog);
	}
    //----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param postpaidLog
	 * @return
	 */
	@Override
	public boolean exists( PostpaidLog postpaidLog ) {
		return super.doExists(postpaidLog);
	}

    //----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database
	 * @return
	 */
	@Override
	public long count() {
		return super.doCountAll();
	}

    //----------------------------------------------------------------------
	@Override
	protected String getSqlSelect() {
		return SQL_SELECT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlInsert() {
		return SQL_INSERT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlUpdate() {
		return SQL_UPDATE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlDelete() {
		return SQL_DELETE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCount() {
		return SQL_COUNT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCountAll() {
		return SQL_COUNT_ALL ;
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForPrimaryKey(PreparedStatement ps, int i, PostpaidLog postpaidLog) throws SQLException {
		//--- Set PRIMARY KEY from bean to PreparedStatement ( SQL "WHERE key=?, ..." )
	}

    //----------------------------------------------------------------------
	@Override
	protected PostpaidLog populateBean(ResultSet rs, PostpaidLog postpaidLog) throws SQLException {

		//--- Set data from ResultSet to Bean attributes
		postpaidLog.setId(rs.getLong("ID")); // java.lang.Long
		if ( rs.wasNull() ) { postpaidLog.setId(null); }; // not primitive number => keep null value if any
		postpaidLog.setBillDate(rs.getDate("BILL_DATE")); // java.util.Date
		postpaidLog.setLogProcess(rs.getDate("LOG_PROCESS")); // java.util.Date
		postpaidLog.setStatus(rs.getString("STATUS")); // java.lang.String
		postpaidLog.setNumRec(rs.getInt("NUM_REC")); // int
		return postpaidLog ;
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForInsert(PreparedStatement ps, int i, PostpaidLog postpaidLog) throws SQLException {

		//--- Set PRIMARY KEY and DATA from bean to PreparedStatement ( SQL "SET x=?, y=?, ..." )
		setValue(ps, i++, postpaidLog.getId() ) ; // "ID" : java.lang.Long
		setValue(ps, i++, postpaidLog.getBillDate() ) ; // "BILL_DATE" : java.util.Date
		setValue(ps, i++, postpaidLog.getLogProcess() ) ; // "LOG_PROCESS" : java.util.Date
		setValue(ps, i++, postpaidLog.getStatus() ) ; // "STATUS" : java.lang.String
		setValue(ps, i++, postpaidLog.getNumRec() ) ; // "NUM_REC" : int
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForUpdate(PreparedStatement ps, int i, PostpaidLog postpaidLog) throws SQLException {

		//--- Set DATA from bean to PreparedStatement ( SQL "SET x=?, y=?, ..." )
		setValue(ps, i++, postpaidLog.getId() ) ; // "ID" : java.lang.Long
		setValue(ps, i++, postpaidLog.getBillDate() ) ; // "BILL_DATE" : java.util.Date
		setValue(ps, i++, postpaidLog.getLogProcess() ) ; // "LOG_PROCESS" : java.util.Date
		setValue(ps, i++, postpaidLog.getStatus() ) ; // "STATUS" : java.lang.String
		setValue(ps, i++, postpaidLog.getNumRec() ) ; // "NUM_REC" : int
		//--- Set PRIMARY KEY from bean to PreparedStatement ( SQL "WHERE key=?, ..." )
	}

}
