/*
 * Created on 23 Jun 2016 ( Time 14:40:51 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package vnp.dao.impl.jdbc;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import vnp.bean.PrizeRewardBuffer;
import vnp.dao.PrizeRewardBufferDAO;
import vnp.dao.impl.jdbc.commons.GenericDAO;

/**
 * PrizeRewardBuffer DAO implementation
 * 
 * @author Telosys Tools
 *
 */
public class PrizeRewardBufferDAOImpl extends GenericDAO<PrizeRewardBuffer> implements PrizeRewardBufferDAO {

	private final static String SQL_SELECT = "select MSISDN, REWARD_CODE, PRIZE_LEVEL, PRIZE_DATE, STATUS from PRIZE_REWARD_BUFFER where ";

	public final static String SQL_INSERT = "insert into PRIZE_REWARD_BUFFER ( MSISDN, REWARD_CODE, PRIZE_LEVEL, PRIZE_DATE, STATUS, CAMPAIGN_ID ) values ( ?, ?, ?, ?, ?,? )";

	private final static String SQL_UPDATE = "update PRIZE_REWARD_BUFFER set MSISDN = ?, REWARD_CODE = ?, PRIZE_LEVEL = ?, PRIZE_DATE = ?, STATUS = ? where ";

	private final static String SQL_DELETE = "delete from PRIZE_REWARD_BUFFER where ";

	private final static String SQL_COUNT_ALL = "select count(*) from PRIZE_REWARD_BUFFER";

	private final static String SQL_COUNT = "select count(*) from PRIZE_REWARD_BUFFER where ";

	// ----------------------------------------------------------------------
	/**
	 * DAO constructor
	 */
	public PrizeRewardBufferDAOImpl() {
		super();
	}

	// ----------------------------------------------------------------------
	/**
	 * Creates a new instance of the bean and populates it with the given
	 * primary value(s)
	 * 
	 * @return the new instance
	 */
	private PrizeRewardBuffer newInstanceWithPrimaryKey() {
		PrizeRewardBuffer prizeRewardBuffer = new PrizeRewardBuffer();
		return prizeRewardBuffer;
	}

	// ----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key
	 * 
	 * @return the bean found or null if not found
	 */
	@Override
	public PrizeRewardBuffer find() {
		PrizeRewardBuffer prizeRewardBuffer = newInstanceWithPrimaryKey();
		if (super.doSelect(prizeRewardBuffer)) {
			return prizeRewardBuffer;
		} else {
			return null; // Not found
		}
	}

	// ----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s)
	 * in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from
	 * the database<br>
	 * If not found, the given instance remains unchanged
	 * 
	 * @param prizeRewardBuffer
	 * @return true if found, false if not found
	 */
	@Override
	public boolean load(PrizeRewardBuffer prizeRewardBuffer) {
		return super.doSelect(prizeRewardBuffer);
	}

	// ----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database
	 * 
	 * @param prizeRewardBuffer
	 */
	@Override
	public void insert(PrizeRewardBuffer prizeRewardBuffer) {
		super.doInsert(prizeRewardBuffer);
	}

	// ----------------------------------------------------------------------
	/**
	 * Updates the given bean in the database
	 * 
	 * @param prizeRewardBuffer
	 * @return
	 */
	@Override
	public int update(PrizeRewardBuffer prizeRewardBuffer) {
		return super.doUpdate(prizeRewardBuffer);
	}

	// ----------------------------------------------------------------------
	/**
	 * Deletes the record in the database using the given primary key value(s)
	 * 
	 * @return
	 */
	@Override
	public int delete() {
		PrizeRewardBuffer prizeRewardBuffer = newInstanceWithPrimaryKey();
		return super.doDelete(prizeRewardBuffer);
	}

	// ----------------------------------------------------------------------
	/**
	 * Deletes the given bean in the database
	 * 
	 * @param prizeRewardBuffer
	 * @return
	 */
	@Override
	public int delete(PrizeRewardBuffer prizeRewardBuffer) {
		return super.doDelete(prizeRewardBuffer);
	}

	// ----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary
	 * key value(s)
	 * 
	 * @return
	 */
	@Override
	public boolean exists() {
		PrizeRewardBuffer prizeRewardBuffer = newInstanceWithPrimaryKey();
		return super.doExists(prizeRewardBuffer);
	}

	// ----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database
	 * 
	 * @param prizeRewardBuffer
	 * @return
	 */
	@Override
	public boolean exists(PrizeRewardBuffer prizeRewardBuffer) {
		return super.doExists(prizeRewardBuffer);
	}

	// ----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database
	 * 
	 * @return
	 */
	@Override
	public long count() {
		return super.doCountAll();
	}

	// ----------------------------------------------------------------------
	@Override
	protected String getSqlSelect() {
		return SQL_SELECT;
	}

	// ----------------------------------------------------------------------
	@Override
	protected String getSqlInsert() {
		return SQL_INSERT;
	}

	// ----------------------------------------------------------------------
	@Override
	protected String getSqlUpdate() {
		return SQL_UPDATE;
	}

	// ----------------------------------------------------------------------
	@Override
	protected String getSqlDelete() {
		return SQL_DELETE;
	}

	// ----------------------------------------------------------------------
	@Override
	protected String getSqlCount() {
		return SQL_COUNT;
	}

	// ----------------------------------------------------------------------
	@Override
	protected String getSqlCountAll() {
		return SQL_COUNT_ALL;
	}

	// ----------------------------------------------------------------------
	@Override
	protected void setValuesForPrimaryKey(PreparedStatement ps, int i, PrizeRewardBuffer prizeRewardBuffer)
			throws SQLException {
		// --- Set PRIMARY KEY from bean to PreparedStatement ( SQL "WHERE
		// key=?, ..." )
	}

	// ----------------------------------------------------------------------
	@Override
	protected PrizeRewardBuffer populateBean(ResultSet rs, PrizeRewardBuffer prizeRewardBuffer) throws SQLException {

		// --- Set data from ResultSet to Bean attributes
		prizeRewardBuffer.setMsisdn(rs.getString("MSISDN")); // java.lang.String
		prizeRewardBuffer.setRewardCode(rs.getLong("REWARD_CODE")); // java.lang.Long
		if (rs.wasNull()) {
			prizeRewardBuffer.setRewardCode(null);
		}
		; // not primitive number => keep null value if any
		prizeRewardBuffer.setPrizeLevel(rs.getInt("PRIZE_LEVEL")); // int
		prizeRewardBuffer.setPrizeDate(rs.getDate("PRIZE_DATE")); // java.util.Date
		prizeRewardBuffer.setStatus(rs.getInt("STATUS")); // int
		return prizeRewardBuffer;
	}

	// ----------------------------------------------------------------------
	@Override
	protected void setValuesForInsert(PreparedStatement ps, int i, PrizeRewardBuffer prizeRewardBuffer)
			throws SQLException {

		// --- Set PRIMARY KEY and DATA from bean to PreparedStatement ( SQL
		// "SET x=?, y=?, ..." )
		setValue(ps, i++, prizeRewardBuffer.getMsisdn()); // "MSISDN" :
															// java.lang.String
		setValue(ps, i++, prizeRewardBuffer.getRewardCode()); // "REWARD_CODE" :
																// java.lang.Long
		setValue(ps, i++, prizeRewardBuffer.getPrizeLevel()); // "PRIZE_LEVEL" :
																// int
		setValue(ps, i++, prizeRewardBuffer.getPrizeDate()); // "PRIZE_DATE" :
																// java.util.Date
		setValue(ps, i++, prizeRewardBuffer.getStatus()); // "STATUS" : int
	}

	// ----------------------------------------------------------------------
	@Override
	protected void setValuesForUpdate(PreparedStatement ps, int i, PrizeRewardBuffer prizeRewardBuffer)
			throws SQLException {

		// --- Set DATA from bean to PreparedStatement ( SQL "SET x=?, y=?, ..."
		// )
		setValue(ps, i++, prizeRewardBuffer.getMsisdn()); // "MSISDN" :
															// java.lang.String
		setValue(ps, i++, prizeRewardBuffer.getRewardCode()); // "REWARD_CODE" :
																// java.lang.Long
		setValue(ps, i++, prizeRewardBuffer.getPrizeLevel()); // "PRIZE_LEVEL" :
																// int
		setValue(ps, i++, prizeRewardBuffer.getPrizeDate()); // "PRIZE_DATE" :
																// java.util.Date
		setValue(ps, i++, prizeRewardBuffer.getStatus()); // "STATUS" : int
		// --- Set PRIMARY KEY from bean to PreparedStatement ( SQL "WHERE
		// key=?, ..." )
	}

}
