/*
 * Created on 7 Jun 2016 ( Time 13:19:55 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package vnp.dao.impl.jdbc;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import vnp.bean.PrizeRewardLog;
import vnp.dao.PrizeRewardLogDAO;
import vnp.dao.impl.jdbc.commons.GenericDAO;

/**
 * PrizeRewardLog DAO implementation 
 * 
 * @author Telosys Tools
 *
 */
public class PrizeRewardLogDAOImpl extends GenericDAO<PrizeRewardLog> implements PrizeRewardLogDAO {

	private final static String SQL_SELECT = 
		"select MSISDN, PRIZE_ID, SUBTYPE, ACTIONLOG, RESULTLOG, DATE_TIME, STATUS from PRIZE_REWARD_LOG where ";

	private final static String SQL_INSERT = 
		"insert into PRIZE_REWARD_LOG ( MSISDN, PRIZE_ID, SUBTYPE, ACTIONLOG, RESULTLOG, DATE_TIME, STATUS ) values ( ?, ?, ?, ?, ?, ?, ? )";

	private final static String SQL_UPDATE = 
		"update PRIZE_REWARD_LOG set MSISDN = ?, PRIZE_ID = ?, SUBTYPE = ?, ACTIONLOG = ?, RESULTLOG = ?, DATE_TIME = ?, STATUS = ? where ";

	private final static String SQL_DELETE = 
		"delete from PRIZE_REWARD_LOG where ";

	private final static String SQL_COUNT_ALL = 
		"select count(*) from PRIZE_REWARD_LOG";

	private final static String SQL_COUNT = 
		"select count(*) from PRIZE_REWARD_LOG where ";

    //----------------------------------------------------------------------
	/**
	 * DAO constructor
	 */
	public PrizeRewardLogDAOImpl() {
		super();
	}

	//----------------------------------------------------------------------
	/**
	 * Creates a new instance of the bean and populates it with the given primary value(s)
	 * @return the new instance
	 */
	private PrizeRewardLog newInstanceWithPrimaryKey(  ) {
		PrizeRewardLog prizeRewardLog = new PrizeRewardLog();
		return prizeRewardLog ;
	}

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @return the bean found or null if not found 
	 */
	@Override
	public PrizeRewardLog find(  ) {
		PrizeRewardLog prizeRewardLog = newInstanceWithPrimaryKey(  ) ;
		if ( super.doSelect(prizeRewardLog) ) {
			return prizeRewardLog ;
		}
		else {
			return null ; // Not found
		}
	}
	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param prizeRewardLog
	 * @return true if found, false if not found
	 */
	@Override
	public boolean load( PrizeRewardLog prizeRewardLog ) {
		return super.doSelect(prizeRewardLog) ;
	}
    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param prizeRewardLog
	 */
	@Override
	public void insert(PrizeRewardLog prizeRewardLog) {
		super.doInsert(prizeRewardLog);
	}	

    //----------------------------------------------------------------------
	/**
	 * Updates the given bean in the database 
	 * @param prizeRewardLog
	 * @return
	 */
	@Override
	public int update(PrizeRewardLog prizeRewardLog) {
		return super.doUpdate(prizeRewardLog);
	}	

    //----------------------------------------------------------------------
	/**
	 * Deletes the record in the database using the given primary key value(s) 
	 * @return
	 */
	@Override
	public int delete(  ) {
		PrizeRewardLog prizeRewardLog = newInstanceWithPrimaryKey(  ) ;
		return super.doDelete(prizeRewardLog);
	}

    //----------------------------------------------------------------------
	/**
	 * Deletes the given bean in the database 
	 * @param prizeRewardLog
	 * @return
	 */
	@Override
	public int delete( PrizeRewardLog prizeRewardLog ) {
		return super.doDelete(prizeRewardLog);
	}

    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @return
	 */
	@Override
	public boolean exists(  ) {
		PrizeRewardLog prizeRewardLog = newInstanceWithPrimaryKey(  ) ;
		return super.doExists(prizeRewardLog);
	}
    //----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param prizeRewardLog
	 * @return
	 */
	@Override
	public boolean exists( PrizeRewardLog prizeRewardLog ) {
		return super.doExists(prizeRewardLog);
	}

    //----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database
	 * @return
	 */
	@Override
	public long count() {
		return super.doCountAll();
	}

    //----------------------------------------------------------------------
	@Override
	protected String getSqlSelect() {
		return SQL_SELECT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlInsert() {
		return SQL_INSERT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlUpdate() {
		return SQL_UPDATE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlDelete() {
		return SQL_DELETE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCount() {
		return SQL_COUNT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCountAll() {
		return SQL_COUNT_ALL ;
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForPrimaryKey(PreparedStatement ps, int i, PrizeRewardLog prizeRewardLog) throws SQLException {
		//--- Set PRIMARY KEY from bean to PreparedStatement ( SQL "WHERE key=?, ..." )
	}

    //----------------------------------------------------------------------
	@Override
	protected PrizeRewardLog populateBean(ResultSet rs, PrizeRewardLog prizeRewardLog) throws SQLException {

		//--- Set data from ResultSet to Bean attributes
		prizeRewardLog.setMsisdn(rs.getString("MSISDN")); // java.lang.String
		prizeRewardLog.setPrizeId(rs.getInt("PRIZE_ID")); // int
		prizeRewardLog.setSubtype(rs.getString("SUBTYPE")); // java.lang.String
		prizeRewardLog.setActionlog(rs.getString("ACTIONLOG")); // java.lang.String
		prizeRewardLog.setResultlog(rs.getString("RESULTLOG")); // java.lang.String
		prizeRewardLog.setDateTime(rs.getDate("DATE_TIME")); // java.util.Date
		prizeRewardLog.setStatus(rs.getInt("STATUS")); // int
		return prizeRewardLog ;
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForInsert(PreparedStatement ps, int i, PrizeRewardLog prizeRewardLog) throws SQLException {

		//--- Set PRIMARY KEY and DATA from bean to PreparedStatement ( SQL "SET x=?, y=?, ..." )
		setValue(ps, i++, prizeRewardLog.getMsisdn() ) ; // "MSISDN" : java.lang.String
		setValue(ps, i++, prizeRewardLog.getPrizeId() ) ; // "PRIZE_ID" : int
		setValue(ps, i++, prizeRewardLog.getSubtype() ) ; // "SUBTYPE" : java.lang.String
		setValue(ps, i++, prizeRewardLog.getActionlog() ) ; // "ACTIONLOG" : java.lang.String
		setValue(ps, i++, prizeRewardLog.getResultlog() ) ; // "RESULTLOG" : java.lang.String
		setValue(ps, i++, prizeRewardLog.getDateTime() ) ; // "DATE_TIME" : java.util.Date
		setValue(ps, i++, prizeRewardLog.getStatus() ) ; // "STATUS" : int
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForUpdate(PreparedStatement ps, int i, PrizeRewardLog prizeRewardLog) throws SQLException {

		//--- Set DATA from bean to PreparedStatement ( SQL "SET x=?, y=?, ..." )
		setValue(ps, i++, prizeRewardLog.getMsisdn() ) ; // "MSISDN" : java.lang.String
		setValue(ps, i++, prizeRewardLog.getPrizeId() ) ; // "PRIZE_ID" : int
		setValue(ps, i++, prizeRewardLog.getSubtype() ) ; // "SUBTYPE" : java.lang.String
		setValue(ps, i++, prizeRewardLog.getActionlog() ) ; // "ACTIONLOG" : java.lang.String
		setValue(ps, i++, prizeRewardLog.getResultlog() ) ; // "RESULTLOG" : java.lang.String
		setValue(ps, i++, prizeRewardLog.getDateTime() ) ; // "DATE_TIME" : java.util.Date
		setValue(ps, i++, prizeRewardLog.getStatus() ) ; // "STATUS" : int
		//--- Set PRIMARY KEY from bean to PreparedStatement ( SQL "WHERE key=?, ..." )
	}

}
