/*
 * Created on 2 Jun 2016 ( Time 17:01:54 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package vnp.dao.impl.jdbc;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import vnp.bean.QueuePrepaidBroadcast;
import vnp.dao.QueuePrepaidBroadcastDAO;
import vnp.dao.impl.jdbc.commons.GenericDAO;

/**
 * QueuePrepaidBroadcast DAO implementation 
 * 
 * @author Telosys Tools
 *
 */
public class QueuePrepaidBroadcastDAOImpl extends GenericDAO<QueuePrepaidBroadcast> implements QueuePrepaidBroadcastDAO {

	private final static String SQL_SELECT = 
		"select MSISDN, DATE_TIME, SMS_CONTENT from QUEUE_PREPAID_BROADCAST where ";

	private final static String SQL_INSERT = 
		"insert into QUEUE_PREPAID_BROADCAST ( MSISDN, DATE_TIME, SMS_CONTENT ) values ( ?, ?, ? )";

	private final static String SQL_UPDATE = 
		"update QUEUE_PREPAID_BROADCAST set MSISDN = ?, DATE_TIME = ?, SMS_CONTENT = ? where ";

	private final static String SQL_DELETE = 
		"delete from QUEUE_PREPAID_BROADCAST where ";

	private final static String SQL_COUNT_ALL = 
		"select count(*) from QUEUE_PREPAID_BROADCAST";

	private final static String SQL_COUNT = 
		"select count(*) from QUEUE_PREPAID_BROADCAST where ";

    //----------------------------------------------------------------------
	/**
	 * DAO constructor
	 */
	public QueuePrepaidBroadcastDAOImpl() {
		super();
	}

	//----------------------------------------------------------------------
	/**
	 * Creates a new instance of the bean and populates it with the given primary value(s)
	 * @return the new instance
	 */
	private QueuePrepaidBroadcast newInstanceWithPrimaryKey(  ) {
		QueuePrepaidBroadcast queuePrepaidBroadcast = new QueuePrepaidBroadcast();
		return queuePrepaidBroadcast ;
	}

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @return the bean found or null if not found 
	 */
	@Override
	public QueuePrepaidBroadcast find(  ) {
		QueuePrepaidBroadcast queuePrepaidBroadcast = newInstanceWithPrimaryKey(  ) ;
		if ( super.doSelect(queuePrepaidBroadcast) ) {
			return queuePrepaidBroadcast ;
		}
		else {
			return null ; // Not found
		}
	}
	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param queuePrepaidBroadcast
	 * @return true if found, false if not found
	 */
	@Override
	public boolean load( QueuePrepaidBroadcast queuePrepaidBroadcast ) {
		return super.doSelect(queuePrepaidBroadcast) ;
	}
    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param queuePrepaidBroadcast
	 */
	@Override
	public void insert(QueuePrepaidBroadcast queuePrepaidBroadcast) {
		super.doInsert(queuePrepaidBroadcast);
	}	

    //----------------------------------------------------------------------
	/**
	 * Updates the given bean in the database 
	 * @param queuePrepaidBroadcast
	 * @return
	 */
	@Override
	public int update(QueuePrepaidBroadcast queuePrepaidBroadcast) {
		return super.doUpdate(queuePrepaidBroadcast);
	}	

    //----------------------------------------------------------------------
	/**
	 * Deletes the record in the database using the given primary key value(s) 
	 * @return
	 */
	@Override
	public int delete(  ) {
		QueuePrepaidBroadcast queuePrepaidBroadcast = newInstanceWithPrimaryKey(  ) ;
		return super.doDelete(queuePrepaidBroadcast);
	}

    //----------------------------------------------------------------------
	/**
	 * Deletes the given bean in the database 
	 * @param queuePrepaidBroadcast
	 * @return
	 */
	@Override
	public int delete( QueuePrepaidBroadcast queuePrepaidBroadcast ) {
		return super.doDelete(queuePrepaidBroadcast);
	}

    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @return
	 */
	@Override
	public boolean exists(  ) {
		QueuePrepaidBroadcast queuePrepaidBroadcast = newInstanceWithPrimaryKey(  ) ;
		return super.doExists(queuePrepaidBroadcast);
	}
    //----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param queuePrepaidBroadcast
	 * @return
	 */
	@Override
	public boolean exists( QueuePrepaidBroadcast queuePrepaidBroadcast ) {
		return super.doExists(queuePrepaidBroadcast);
	}

    //----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database
	 * @return
	 */
	@Override
	public long count() {
		return super.doCountAll();
	}

    //----------------------------------------------------------------------
	@Override
	protected String getSqlSelect() {
		return SQL_SELECT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlInsert() {
		return SQL_INSERT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlUpdate() {
		return SQL_UPDATE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlDelete() {
		return SQL_DELETE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCount() {
		return SQL_COUNT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCountAll() {
		return SQL_COUNT_ALL ;
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForPrimaryKey(PreparedStatement ps, int i, QueuePrepaidBroadcast queuePrepaidBroadcast) throws SQLException {
		//--- Set PRIMARY KEY from bean to PreparedStatement ( SQL "WHERE key=?, ..." )
	}

    //----------------------------------------------------------------------
	@Override
	protected QueuePrepaidBroadcast populateBean(ResultSet rs, QueuePrepaidBroadcast queuePrepaidBroadcast) throws SQLException {

		//--- Set data from ResultSet to Bean attributes
		queuePrepaidBroadcast.setMsisdn(rs.getString("MSISDN")); // java.lang.String
		queuePrepaidBroadcast.setDateTime(rs.getDate("DATE_TIME")); // java.util.Date
		queuePrepaidBroadcast.setSmsContent(rs.getString("SMS_CONTENT")); // java.lang.String
		return queuePrepaidBroadcast ;
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForInsert(PreparedStatement ps, int i, QueuePrepaidBroadcast queuePrepaidBroadcast) throws SQLException {

		//--- Set PRIMARY KEY and DATA from bean to PreparedStatement ( SQL "SET x=?, y=?, ..." )
		setValue(ps, i++, queuePrepaidBroadcast.getMsisdn() ) ; // "MSISDN" : java.lang.String
		setValue(ps, i++, queuePrepaidBroadcast.getDateTime() ) ; // "DATE_TIME" : java.util.Date
		setValue(ps, i++, queuePrepaidBroadcast.getSmsContent() ) ; // "SMS_CONTENT" : java.lang.String
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForUpdate(PreparedStatement ps, int i, QueuePrepaidBroadcast queuePrepaidBroadcast) throws SQLException {

		//--- Set DATA from bean to PreparedStatement ( SQL "SET x=?, y=?, ..." )
		setValue(ps, i++, queuePrepaidBroadcast.getMsisdn() ) ; // "MSISDN" : java.lang.String
		setValue(ps, i++, queuePrepaidBroadcast.getDateTime() ) ; // "DATE_TIME" : java.util.Date
		setValue(ps, i++, queuePrepaidBroadcast.getSmsContent() ) ; // "SMS_CONTENT" : java.lang.String
		//--- Set PRIMARY KEY from bean to PreparedStatement ( SQL "WHERE key=?, ..." )
	}

}
