/*
 * Created on 2 Jun 2016 ( Time 17:01:53 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package vnp.dao.impl.jdbc;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import vnp.bean.QueuePostpaidBroadcast;
import vnp.dao.QueuePostpaidBroadcastDAO;
import vnp.dao.impl.jdbc.commons.GenericDAO;

/**
 * QueuePostpaidBroadcast DAO implementation 
 * 
 * @author Telosys Tools
 *
 */
public class QueuePostpaidBroadcastDAOImpl extends GenericDAO<QueuePostpaidBroadcast> implements QueuePostpaidBroadcastDAO {

	private final static String SQL_SELECT = 
		"select MSISDN, DATE_TIME, SMS_CONTENT from QUEUE_POSTPAID_BROADCAST where ";

	private final static String SQL_INSERT = 
		"insert into QUEUE_POSTPAID_BROADCAST ( MSISDN, DATE_TIME, SMS_CONTENT ) values ( ?, ?, ? )";

	private final static String SQL_UPDATE = 
		"update QUEUE_POSTPAID_BROADCAST set MSISDN = ?, DATE_TIME = ?, SMS_CONTENT = ? where ";

	private final static String SQL_DELETE = 
		"delete from QUEUE_POSTPAID_BROADCAST where ";

	private final static String SQL_COUNT_ALL = 
		"select count(*) from QUEUE_POSTPAID_BROADCAST";

	private final static String SQL_COUNT = 
		"select count(*) from QUEUE_POSTPAID_BROADCAST where ";

    //----------------------------------------------------------------------
	/**
	 * DAO constructor
	 */
	public QueuePostpaidBroadcastDAOImpl() {
		super();
	}

	//----------------------------------------------------------------------
	/**
	 * Creates a new instance of the bean and populates it with the given primary value(s)
	 * @return the new instance
	 */
	private QueuePostpaidBroadcast newInstanceWithPrimaryKey(  ) {
		QueuePostpaidBroadcast queuePostpaidBroadcast = new QueuePostpaidBroadcast();
		return queuePostpaidBroadcast ;
	}

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @return the bean found or null if not found 
	 */
	@Override
	public QueuePostpaidBroadcast find(  ) {
		QueuePostpaidBroadcast queuePostpaidBroadcast = newInstanceWithPrimaryKey(  ) ;
		if ( super.doSelect(queuePostpaidBroadcast) ) {
			return queuePostpaidBroadcast ;
		}
		else {
			return null ; // Not found
		}
	}
	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param queuePostpaidBroadcast
	 * @return true if found, false if not found
	 */
	@Override
	public boolean load( QueuePostpaidBroadcast queuePostpaidBroadcast ) {
		return super.doSelect(queuePostpaidBroadcast) ;
	}
    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param queuePostpaidBroadcast
	 */
	@Override
	public void insert(QueuePostpaidBroadcast queuePostpaidBroadcast) {
		super.doInsert(queuePostpaidBroadcast);
	}	

    //----------------------------------------------------------------------
	/**
	 * Updates the given bean in the database 
	 * @param queuePostpaidBroadcast
	 * @return
	 */
	@Override
	public int update(QueuePostpaidBroadcast queuePostpaidBroadcast) {
		return super.doUpdate(queuePostpaidBroadcast);
	}	

    //----------------------------------------------------------------------
	/**
	 * Deletes the record in the database using the given primary key value(s) 
	 * @return
	 */
	@Override
	public int delete(  ) {
		QueuePostpaidBroadcast queuePostpaidBroadcast = newInstanceWithPrimaryKey(  ) ;
		return super.doDelete(queuePostpaidBroadcast);
	}

    //----------------------------------------------------------------------
	/**
	 * Deletes the given bean in the database 
	 * @param queuePostpaidBroadcast
	 * @return
	 */
	@Override
	public int delete( QueuePostpaidBroadcast queuePostpaidBroadcast ) {
		return super.doDelete(queuePostpaidBroadcast);
	}

    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @return
	 */
	@Override
	public boolean exists(  ) {
		QueuePostpaidBroadcast queuePostpaidBroadcast = newInstanceWithPrimaryKey(  ) ;
		return super.doExists(queuePostpaidBroadcast);
	}
    //----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param queuePostpaidBroadcast
	 * @return
	 */
	@Override
	public boolean exists( QueuePostpaidBroadcast queuePostpaidBroadcast ) {
		return super.doExists(queuePostpaidBroadcast);
	}

    //----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database
	 * @return
	 */
	@Override
	public long count() {
		return super.doCountAll();
	}

    //----------------------------------------------------------------------
	@Override
	protected String getSqlSelect() {
		return SQL_SELECT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlInsert() {
		return SQL_INSERT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlUpdate() {
		return SQL_UPDATE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlDelete() {
		return SQL_DELETE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCount() {
		return SQL_COUNT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCountAll() {
		return SQL_COUNT_ALL ;
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForPrimaryKey(PreparedStatement ps, int i, QueuePostpaidBroadcast queuePostpaidBroadcast) throws SQLException {
		//--- Set PRIMARY KEY from bean to PreparedStatement ( SQL "WHERE key=?, ..." )
	}

    //----------------------------------------------------------------------
	@Override
	protected QueuePostpaidBroadcast populateBean(ResultSet rs, QueuePostpaidBroadcast queuePostpaidBroadcast) throws SQLException {

		//--- Set data from ResultSet to Bean attributes
		queuePostpaidBroadcast.setMsisdn(rs.getString("MSISDN")); // java.lang.String
		queuePostpaidBroadcast.setDateTime(rs.getDate("DATE_TIME")); // java.util.Date
		queuePostpaidBroadcast.setSmsContent(rs.getString("SMS_CONTENT")); // java.lang.String
		return queuePostpaidBroadcast ;
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForInsert(PreparedStatement ps, int i, QueuePostpaidBroadcast queuePostpaidBroadcast) throws SQLException {

		//--- Set PRIMARY KEY and DATA from bean to PreparedStatement ( SQL "SET x=?, y=?, ..." )
		setValue(ps, i++, queuePostpaidBroadcast.getMsisdn() ) ; // "MSISDN" : java.lang.String
		setValue(ps, i++, queuePostpaidBroadcast.getDateTime() ) ; // "DATE_TIME" : java.util.Date
		setValue(ps, i++, queuePostpaidBroadcast.getSmsContent() ) ; // "SMS_CONTENT" : java.lang.String
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForUpdate(PreparedStatement ps, int i, QueuePostpaidBroadcast queuePostpaidBroadcast) throws SQLException {

		//--- Set DATA from bean to PreparedStatement ( SQL "SET x=?, y=?, ..." )
		setValue(ps, i++, queuePostpaidBroadcast.getMsisdn() ) ; // "MSISDN" : java.lang.String
		setValue(ps, i++, queuePostpaidBroadcast.getDateTime() ) ; // "DATE_TIME" : java.util.Date
		setValue(ps, i++, queuePostpaidBroadcast.getSmsContent() ) ; // "SMS_CONTENT" : java.lang.String
		//--- Set PRIMARY KEY from bean to PreparedStatement ( SQL "WHERE key=?, ..." )
	}

}
