/*
 * Created on 2 Jun 2016 ( Time 17:03:04 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package vnp.dao.impl.jdbc;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import vnp.bean.SmsLog;
import vnp.dao.SmsLogDAO;
import vnp.dao.impl.jdbc.commons.GenericDAO;

/**
 * SmsLog DAO implementation 
 * 
 * @author Telosys Tools
 *
 */
public class SmsLogDAOImpl extends GenericDAO<SmsLog> implements SmsLogDAO {

	private final static String SQL_SELECT = 
		"select ID, MSISDN, RECEIVER_TIME, SMS_CONTENT, STATUS, RESPONSE_CONTENT, RESPONSE_TIME, NOTE from SMS_LOG where ";

	private final static String SQL_INSERT = 
		"insert into SMS_LOG ( ID, MSISDN, RECEIVER_TIME, SMS_CONTENT, STATUS, RESPONSE_CONTENT, RESPONSE_TIME, NOTE ) values ( ?, ?, ?, ?, ?, ?, ?, ? )";

	private final static String SQL_UPDATE = 
		"update SMS_LOG set ID = ?, MSISDN = ?, RECEIVER_TIME = ?, SMS_CONTENT = ?, STATUS = ?, RESPONSE_CONTENT = ?, RESPONSE_TIME = ?, NOTE = ? where ";

	private final static String SQL_DELETE = 
		"delete from SMS_LOG where ";

	private final static String SQL_COUNT_ALL = 
		"select count(*) from SMS_LOG";

	private final static String SQL_COUNT = 
		"select count(*) from SMS_LOG where ";

    //----------------------------------------------------------------------
	/**
	 * DAO constructor
	 */
	public SmsLogDAOImpl() {
		super();
	}

	//----------------------------------------------------------------------
	/**
	 * Creates a new instance of the bean and populates it with the given primary value(s)
	 * @return the new instance
	 */
	private SmsLog newInstanceWithPrimaryKey(  ) {
		SmsLog smsLog = new SmsLog();
		return smsLog ;
	}

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @return the bean found or null if not found 
	 */
	@Override
	public SmsLog find(  ) {
		SmsLog smsLog = newInstanceWithPrimaryKey(  ) ;
		if ( super.doSelect(smsLog) ) {
			return smsLog ;
		}
		else {
			return null ; // Not found
		}
	}
	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param smsLog
	 * @return true if found, false if not found
	 */
	@Override
	public boolean load( SmsLog smsLog ) {
		return super.doSelect(smsLog) ;
	}
    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param smsLog
	 */
	@Override
	public void insert(SmsLog smsLog) {
		super.doInsert(smsLog);
	}	

    //----------------------------------------------------------------------
	/**
	 * Updates the given bean in the database 
	 * @param smsLog
	 * @return
	 */
	@Override
	public int update(SmsLog smsLog) {
		return super.doUpdate(smsLog);
	}	

    //----------------------------------------------------------------------
	/**
	 * Deletes the record in the database using the given primary key value(s) 
	 * @return
	 */
	@Override
	public int delete(  ) {
		SmsLog smsLog = newInstanceWithPrimaryKey(  ) ;
		return super.doDelete(smsLog);
	}

    //----------------------------------------------------------------------
	/**
	 * Deletes the given bean in the database 
	 * @param smsLog
	 * @return
	 */
	@Override
	public int delete( SmsLog smsLog ) {
		return super.doDelete(smsLog);
	}

    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @return
	 */
	@Override
	public boolean exists(  ) {
		SmsLog smsLog = newInstanceWithPrimaryKey(  ) ;
		return super.doExists(smsLog);
	}
    //----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param smsLog
	 * @return
	 */
	@Override
	public boolean exists( SmsLog smsLog ) {
		return super.doExists(smsLog);
	}

    //----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database
	 * @return
	 */
	@Override
	public long count() {
		return super.doCountAll();
	}

    //----------------------------------------------------------------------
	@Override
	protected String getSqlSelect() {
		return SQL_SELECT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlInsert() {
		return SQL_INSERT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlUpdate() {
		return SQL_UPDATE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlDelete() {
		return SQL_DELETE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCount() {
		return SQL_COUNT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCountAll() {
		return SQL_COUNT_ALL ;
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForPrimaryKey(PreparedStatement ps, int i, SmsLog smsLog) throws SQLException {
		//--- Set PRIMARY KEY from bean to PreparedStatement ( SQL "WHERE key=?, ..." )
	}

    //----------------------------------------------------------------------
	@Override
	protected SmsLog populateBean(ResultSet rs, SmsLog smsLog) throws SQLException {

		//--- Set data from ResultSet to Bean attributes
		smsLog.setId(rs.getBigDecimal("ID")); // java.math.BigDecimal
		if ( rs.wasNull() ) { smsLog.setId(null); }; // not primitive number => keep null value if any
		smsLog.setMsisdn(rs.getString("MSISDN")); // java.lang.String
		smsLog.setReceiverTime(rs.getDate("RECEIVER_TIME")); // java.util.Date
		smsLog.setSmsContent(rs.getString("SMS_CONTENT")); // java.lang.String
		smsLog.setStatus(rs.getBigDecimal("STATUS")); // java.math.BigDecimal
		if ( rs.wasNull() ) { smsLog.setStatus(null); }; // not primitive number => keep null value if any
		smsLog.setResponseContent(rs.getString("RESPONSE_CONTENT")); // java.lang.String
		smsLog.setResponseTime(rs.getDate("RESPONSE_TIME")); // java.util.Date
		smsLog.setNote(rs.getString("NOTE")); // java.lang.String
		return smsLog ;
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForInsert(PreparedStatement ps, int i, SmsLog smsLog) throws SQLException {

		//--- Set PRIMARY KEY and DATA from bean to PreparedStatement ( SQL "SET x=?, y=?, ..." )
		setValue(ps, i++, smsLog.getId() ) ; // "ID" : java.math.BigDecimal
		setValue(ps, i++, smsLog.getMsisdn() ) ; // "MSISDN" : java.lang.String
		setValue(ps, i++, smsLog.getReceiverTime() ) ; // "RECEIVER_TIME" : java.util.Date
		setValue(ps, i++, smsLog.getSmsContent() ) ; // "SMS_CONTENT" : java.lang.String
		setValue(ps, i++, smsLog.getStatus() ) ; // "STATUS" : java.math.BigDecimal
		setValue(ps, i++, smsLog.getResponseContent() ) ; // "RESPONSE_CONTENT" : java.lang.String
		setValue(ps, i++, smsLog.getResponseTime() ) ; // "RESPONSE_TIME" : java.util.Date
		setValue(ps, i++, smsLog.getNote() ) ; // "NOTE" : java.lang.String
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForUpdate(PreparedStatement ps, int i, SmsLog smsLog) throws SQLException {

		//--- Set DATA from bean to PreparedStatement ( SQL "SET x=?, y=?, ..." )
		setValue(ps, i++, smsLog.getId() ) ; // "ID" : java.math.BigDecimal
		setValue(ps, i++, smsLog.getMsisdn() ) ; // "MSISDN" : java.lang.String
		setValue(ps, i++, smsLog.getReceiverTime() ) ; // "RECEIVER_TIME" : java.util.Date
		setValue(ps, i++, smsLog.getSmsContent() ) ; // "SMS_CONTENT" : java.lang.String
		setValue(ps, i++, smsLog.getStatus() ) ; // "STATUS" : java.math.BigDecimal
		setValue(ps, i++, smsLog.getResponseContent() ) ; // "RESPONSE_CONTENT" : java.lang.String
		setValue(ps, i++, smsLog.getResponseTime() ) ; // "RESPONSE_TIME" : java.util.Date
		setValue(ps, i++, smsLog.getNote() ) ; // "NOTE" : java.lang.String
		//--- Set PRIMARY KEY from bean to PreparedStatement ( SQL "WHERE key=?, ..." )
	}

}
