/*
 * Created on 3 Jun 2016 ( Time 16:24:32 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package vnp.dao.impl.jdbc;

import java.math.BigDecimal;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import vnp.bean.SmsMt;
import vnp.dao.SmsMtDAO;
import vnp.dao.impl.jdbc.commons.GenericDAO;

/**
 * SmsMt DAO implementation
 * 
 * @author Telosys Tools
 *
 */
public class SmsMtDAOImpl extends GenericDAO<SmsMt> implements SmsMtDAO {

	private final static String SQL_SELECT = "select ID, MSISDN, SUBMIT_TIME, SMS_CONTENT, MO_ID, STATUS, SENT_TIME from SMS_MT where ID = ?";

	private final static String SQL_INSERT = "insert into SMS_MT ( ID, MSISDN, SUBMIT_TIME, SMS_CONTENT, MO_ID, STATUS, SENT_TIME ) values ( ?, ?, ?, ?, ?, ?, ? )";

	private final static String SQL_UPDATE = "update SMS_MT set MSISDN = ?, SUBMIT_TIME = ?, SMS_CONTENT = ?, MO_ID = ?, STATUS = ?, SENT_TIME = ? where ID = ?";

	private final static String SQL_DELETE = "delete from SMS_MT where ID = ?";

	private final static String SQL_COUNT_ALL = "select count(*) from SMS_MT";

	private final static String SQL_COUNT = "select count(*) from SMS_MT where ID = ?";

	// ----------------------------------------------------------------------
	/**
	 * DAO constructor
	 */
	public SmsMtDAOImpl() {
		super();
	}

	// ----------------------------------------------------------------------
	/**
	 * Creates a new instance of the bean and populates it with the given
	 * primary value(s)
	 * 
	 * @param id;
	 * @return the new instance
	 */
	private SmsMt newInstanceWithPrimaryKey(BigDecimal id) {
		SmsMt smsMt = new SmsMt();
		smsMt.setId(id);
		return smsMt;
	}

	// ----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key
	 * 
	 * @param id;
	 * @return the bean found or null if not found
	 */
	@Override
	public SmsMt find(BigDecimal id) {
		SmsMt smsMt = newInstanceWithPrimaryKey(id);
		if (super.doSelect(smsMt)) {
			return smsMt;
		} else {
			return null; // Not found
		}
	}

	// ----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s)
	 * in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from
	 * the database<br>
	 * If not found, the given instance remains unchanged
	 * 
	 * @param smsMt
	 * @return true if found, false if not found
	 */
	@Override
	public boolean load(SmsMt smsMt) {
		return super.doSelect(smsMt);
	}

	// ----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database
	 * 
	 * @param smsMt
	 */
	@Override
	public void insert(SmsMt smsMt) {
		super.doInsert(smsMt);
	}

	// ----------------------------------------------------------------------
	/**
	 * Updates the given bean in the database
	 * 
	 * @param smsMt
	 * @return
	 */
	@Override
	public int update(SmsMt smsMt) {
		return super.doUpdate(smsMt);
	}

	// ----------------------------------------------------------------------
	/**
	 * Deletes the record in the database using the given primary key value(s)
	 * 
	 * @param id;
	 * @return
	 */
	@Override
	public int delete(BigDecimal id) {
		SmsMt smsMt = newInstanceWithPrimaryKey(id);
		return super.doDelete(smsMt);
	}

	// ----------------------------------------------------------------------
	/**
	 * Deletes the given bean in the database
	 * 
	 * @param smsMt
	 * @return
	 */
	@Override
	public int delete(SmsMt smsMt) {
		return super.doDelete(smsMt);
	}

	// ----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary
	 * key value(s)
	 * 
	 * @param id;
	 * @return
	 */
	@Override
	public boolean exists(BigDecimal id) {
		SmsMt smsMt = newInstanceWithPrimaryKey(id);
		return super.doExists(smsMt);
	}

	// ----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database
	 * 
	 * @param smsMt
	 * @return
	 */
	@Override
	public boolean exists(SmsMt smsMt) {
		return super.doExists(smsMt);
	}

	// ----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database
	 * 
	 * @return
	 */
	@Override
	public long count() {
		return super.doCountAll();
	}

	// ----------------------------------------------------------------------
	@Override
	protected String getSqlSelect() {
		return SQL_SELECT;
	}

	// ----------------------------------------------------------------------
	@Override
	protected String getSqlInsert() {
		return SQL_INSERT;
	}

	// ----------------------------------------------------------------------
	@Override
	protected String getSqlUpdate() {
		return SQL_UPDATE;
	}

	// ----------------------------------------------------------------------
	@Override
	protected String getSqlDelete() {
		return SQL_DELETE;
	}

	// ----------------------------------------------------------------------
	@Override
	protected String getSqlCount() {
		return SQL_COUNT;
	}

	// ----------------------------------------------------------------------
	@Override
	protected String getSqlCountAll() {
		return SQL_COUNT_ALL;
	}

	// ----------------------------------------------------------------------
	@Override
	protected void setValuesForPrimaryKey(PreparedStatement ps, int i, SmsMt smsMt) throws SQLException {
		// --- Set PRIMARY KEY from bean to PreparedStatement ( SQL "WHERE
		// key=?, ..." )
		setValue(ps, i++, smsMt.getId()); // "ID" : java.math.BigDecimal
	}

	// ----------------------------------------------------------------------
	@Override
	protected SmsMt populateBean(ResultSet rs, SmsMt smsMt) throws SQLException {

		// --- Set data from ResultSet to Bean attributes
		smsMt.setId(rs.getBigDecimal("ID")); // java.math.BigDecimal
		if (rs.wasNull()) {
			smsMt.setId(null);
		}
		; // not primitive number => keep null value if any
		smsMt.setMsisdn(rs.getString("MSISDN")); // java.lang.String
		smsMt.setSubmitTime(rs.getDate("SUBMIT_TIME")); // java.util.Date
		smsMt.setSmsContent(rs.getString("SMS_CONTENT")); // java.lang.String
		smsMt.setMoId(rs.getLong("MO_ID")); // java.math.BigDecimal
		// not primitive number => keep null value if any
		smsMt.setStatus(rs.getBigDecimal("STATUS")); // java.math.BigDecimal
		if (rs.wasNull()) {
			smsMt.setStatus(null);
		}
		; // not primitive number => keep null value if any
		smsMt.setSentTime(rs.getDate("SENT_TIME")); // java.util.Date
		return smsMt;
	}

	// ----------------------------------------------------------------------
	@Override
	protected void setValuesForInsert(PreparedStatement ps, int i, SmsMt smsMt) throws SQLException {

		// --- Set PRIMARY KEY and DATA from bean to PreparedStatement ( SQL
		// "SET x=?, y=?, ..." )
		setValue(ps, i++, smsMt.getId()); // "ID" : java.math.BigDecimal
		setValue(ps, i++, smsMt.getMsisdn()); // "MSISDN" : java.lang.String
		setValue(ps, i++, smsMt.getSubmitTime()); // "SUBMIT_TIME" :
													// java.util.Date
		setValue(ps, i++, smsMt.getSmsContent()); // "SMS_CONTENT" :
													// java.lang.String
		setValue(ps, i++, smsMt.getMoId()); // "MO_ID" : java.math.BigDecimal
		setValue(ps, i++, smsMt.getStatus()); // "STATUS" : java.math.BigDecimal
		setValue(ps, i++, smsMt.getSentTime()); // "SENT_TIME" : java.util.Date
	}

	// ----------------------------------------------------------------------
	@Override
	protected void setValuesForUpdate(PreparedStatement ps, int i, SmsMt smsMt) throws SQLException {

		// --- Set DATA from bean to PreparedStatement ( SQL "SET x=?, y=?, ..."
		// )
		setValue(ps, i++, smsMt.getMsisdn()); // "MSISDN" : java.lang.String
		setValue(ps, i++, smsMt.getSubmitTime()); // "SUBMIT_TIME" :
													// java.util.Date
		setValue(ps, i++, smsMt.getSmsContent()); // "SMS_CONTENT" :
													// java.lang.String
		setValue(ps, i++, smsMt.getMoId()); // "MO_ID" : java.math.BigDecimal
		setValue(ps, i++, smsMt.getStatus()); // "STATUS" : java.math.BigDecimal
		setValue(ps, i++, smsMt.getSentTime()); // "SENT_TIME" : java.util.Date
		// --- Set PRIMARY KEY from bean to PreparedStatement ( SQL "WHERE
		// key=?, ..." )
		setValue(ps, i++, smsMt.getId()); // "ID" : java.math.BigDecimal
	}

}
