/*
 * Created on 17 Jun 2016 ( Time 12:35:41 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package vnp.dao.impl.jdbc;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import vnp.bean.SubInAccumulate;
import vnp.dao.SubInAccumulateDAO;
import vnp.dao.impl.jdbc.commons.GenericDAO;

/**
 * SubInAccumulate DAO implementation 
 * 
 * @author Telosys Tools
 *
 */
public class SubInAccumulateDAOImpl extends GenericDAO<SubInAccumulate> implements SubInAccumulateDAO {

	private final static String SQL_SELECT = 
		"select MSISDN, ACC_VALUE, LAST_ACC_VALUE, CODE_COUNT, LAST_CODE_COUNT, DATE_TIME from SUB_IN_ACCUMULATE where ";

	private final static String SQL_INSERT = 
		"insert into SUB_IN_ACCUMULATE ( MSISDN, ACC_VALUE, LAST_ACC_VALUE, CODE_COUNT, LAST_CODE_COUNT, DATE_TIME ) values ( ?, ?, ?, ?, ?, ? )";

	private final static String SQL_UPDATE = 
		"update SUB_IN_ACCUMULATE set MSISDN = ?, ACC_VALUE = ?, LAST_ACC_VALUE = ?, CODE_COUNT = ?, LAST_CODE_COUNT = ?, DATE_TIME = ? where ";

	private final static String SQL_DELETE = 
		"delete from SUB_IN_ACCUMULATE where ";

	private final static String SQL_COUNT_ALL = 
		"select count(*) from SUB_IN_ACCUMULATE";

	private final static String SQL_COUNT = 
		"select count(*) from SUB_IN_ACCUMULATE where ";

    //----------------------------------------------------------------------
	/**
	 * DAO constructor
	 */
	public SubInAccumulateDAOImpl() {
		super();
	}

	//----------------------------------------------------------------------
	/**
	 * Creates a new instance of the bean and populates it with the given primary value(s)
	 * @return the new instance
	 */
	private SubInAccumulate newInstanceWithPrimaryKey(  ) {
		SubInAccumulate subInAccumulate = new SubInAccumulate();
		return subInAccumulate ;
	}

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @return the bean found or null if not found 
	 */
	@Override
	public SubInAccumulate find(  ) {
		SubInAccumulate subInAccumulate = newInstanceWithPrimaryKey(  ) ;
		if ( super.doSelect(subInAccumulate) ) {
			return subInAccumulate ;
		}
		else {
			return null ; // Not found
		}
	}
	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param subInAccumulate
	 * @return true if found, false if not found
	 */
	@Override
	public boolean load( SubInAccumulate subInAccumulate ) {
		return super.doSelect(subInAccumulate) ;
	}
    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param subInAccumulate
	 */
	@Override
	public void insert(SubInAccumulate subInAccumulate) {
		super.doInsert(subInAccumulate);
	}	

    //----------------------------------------------------------------------
	/**
	 * Updates the given bean in the database 
	 * @param subInAccumulate
	 * @return
	 */
	@Override
	public int update(SubInAccumulate subInAccumulate) {
		return super.doUpdate(subInAccumulate);
	}	

    //----------------------------------------------------------------------
	/**
	 * Deletes the record in the database using the given primary key value(s) 
	 * @return
	 */
	@Override
	public int delete(  ) {
		SubInAccumulate subInAccumulate = newInstanceWithPrimaryKey(  ) ;
		return super.doDelete(subInAccumulate);
	}

    //----------------------------------------------------------------------
	/**
	 * Deletes the given bean in the database 
	 * @param subInAccumulate
	 * @return
	 */
	@Override
	public int delete( SubInAccumulate subInAccumulate ) {
		return super.doDelete(subInAccumulate);
	}

    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @return
	 */
	@Override
	public boolean exists(  ) {
		SubInAccumulate subInAccumulate = newInstanceWithPrimaryKey(  ) ;
		return super.doExists(subInAccumulate);
	}
    //----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param subInAccumulate
	 * @return
	 */
	@Override
	public boolean exists( SubInAccumulate subInAccumulate ) {
		return super.doExists(subInAccumulate);
	}

    //----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database
	 * @return
	 */
	@Override
	public long count() {
		return super.doCountAll();
	}

    //----------------------------------------------------------------------
	@Override
	protected String getSqlSelect() {
		return SQL_SELECT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlInsert() {
		return SQL_INSERT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlUpdate() {
		return SQL_UPDATE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlDelete() {
		return SQL_DELETE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCount() {
		return SQL_COUNT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCountAll() {
		return SQL_COUNT_ALL ;
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForPrimaryKey(PreparedStatement ps, int i, SubInAccumulate subInAccumulate) throws SQLException {
		//--- Set PRIMARY KEY from bean to PreparedStatement ( SQL "WHERE key=?, ..." )
	}

    //----------------------------------------------------------------------
	@Override
	protected SubInAccumulate populateBean(ResultSet rs, SubInAccumulate subInAccumulate) throws SQLException {

		//--- Set data from ResultSet to Bean attributes
		subInAccumulate.setMsisdn(rs.getString("MSISDN")); // java.lang.String
		subInAccumulate.setAccValue(rs.getBigDecimal("ACC_VALUE")); // java.math.BigDecimal
		if ( rs.wasNull() ) { subInAccumulate.setAccValue(null); }; // not primitive number => keep null value if any
		subInAccumulate.setLastAccValue(rs.getBigDecimal("LAST_ACC_VALUE")); // java.math.BigDecimal
		if ( rs.wasNull() ) { subInAccumulate.setLastAccValue(null); }; // not primitive number => keep null value if any
		subInAccumulate.setCodeCount(rs.getInt("CODE_COUNT")); // int
		subInAccumulate.setLastCodeCount(rs.getInt("LAST_CODE_COUNT")); // int
		subInAccumulate.setDateTime(rs.getDate("DATE_TIME")); // java.util.Date
		return subInAccumulate ;
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForInsert(PreparedStatement ps, int i, SubInAccumulate subInAccumulate) throws SQLException {

		//--- Set PRIMARY KEY and DATA from bean to PreparedStatement ( SQL "SET x=?, y=?, ..." )
		setValue(ps, i++, subInAccumulate.getMsisdn() ) ; // "MSISDN" : java.lang.String
		setValue(ps, i++, subInAccumulate.getAccValue() ) ; // "ACC_VALUE" : java.math.BigDecimal
		setValue(ps, i++, subInAccumulate.getLastAccValue() ) ; // "LAST_ACC_VALUE" : java.math.BigDecimal
		setValue(ps, i++, subInAccumulate.getCodeCount() ) ; // "CODE_COUNT" : int
		setValue(ps, i++, subInAccumulate.getLastCodeCount() ) ; // "LAST_CODE_COUNT" : int
		setValue(ps, i++, subInAccumulate.getDateTime() ) ; // "DATE_TIME" : java.util.Date
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForUpdate(PreparedStatement ps, int i, SubInAccumulate subInAccumulate) throws SQLException {

		//--- Set DATA from bean to PreparedStatement ( SQL "SET x=?, y=?, ..." )
		setValue(ps, i++, subInAccumulate.getMsisdn() ) ; // "MSISDN" : java.lang.String
		setValue(ps, i++, subInAccumulate.getAccValue() ) ; // "ACC_VALUE" : java.math.BigDecimal
		setValue(ps, i++, subInAccumulate.getLastAccValue() ) ; // "LAST_ACC_VALUE" : java.math.BigDecimal
		setValue(ps, i++, subInAccumulate.getCodeCount() ) ; // "CODE_COUNT" : int
		setValue(ps, i++, subInAccumulate.getLastCodeCount() ) ; // "LAST_CODE_COUNT" : int
		setValue(ps, i++, subInAccumulate.getDateTime() ) ; // "DATE_TIME" : java.util.Date
		//--- Set PRIMARY KEY from bean to PreparedStatement ( SQL "WHERE key=?, ..." )
	}

}
