/*
 * Created on 17 Jun 2016 ( Time 12:35:41 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package vnp.dao.impl.jdbc;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import vnp.bean.SubPostAccumulate;
import vnp.dao.SubPostAccumulateDAO;
import vnp.dao.impl.jdbc.commons.GenericDAO;

/**
 * SubPostAccumulate DAO implementation 
 * 
 * @author Telosys Tools
 *
 */
public class SubPostAccumulateDAOImpl extends GenericDAO<SubPostAccumulate> implements SubPostAccumulateDAO {

	private final static String SQL_SELECT = 
		"select MSISDN, ACC_VALUE, LAST_ACC_VALUE, CODE_COUNT, LAST_CODE_COUNT, DATE_TIME from SUB_POST_ACCUMULATE where ";

	private final static String SQL_INSERT = 
		"insert into SUB_POST_ACCUMULATE ( MSISDN, ACC_VALUE, LAST_ACC_VALUE, CODE_COUNT, LAST_CODE_COUNT, DATE_TIME ) values ( ?, ?, ?, ?, ?, ? )";

	private final static String SQL_UPDATE = 
		"update SUB_POST_ACCUMULATE set MSISDN = ?, ACC_VALUE = ?, LAST_ACC_VALUE = ?, CODE_COUNT = ?, LAST_CODE_COUNT = ?, DATE_TIME = ? where ";

	private final static String SQL_DELETE = 
		"delete from SUB_POST_ACCUMULATE where ";

	private final static String SQL_COUNT_ALL = 
		"select count(*) from SUB_POST_ACCUMULATE";

	private final static String SQL_COUNT = 
		"select count(*) from SUB_POST_ACCUMULATE where ";

    //----------------------------------------------------------------------
	/**
	 * DAO constructor
	 */
	public SubPostAccumulateDAOImpl() {
		super();
	}

	//----------------------------------------------------------------------
	/**
	 * Creates a new instance of the bean and populates it with the given primary value(s)
	 * @return the new instance
	 */
	private SubPostAccumulate newInstanceWithPrimaryKey(  ) {
		SubPostAccumulate subPostAccumulate = new SubPostAccumulate();
		return subPostAccumulate ;
	}

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @return the bean found or null if not found 
	 */
	@Override
	public SubPostAccumulate find(  ) {
		SubPostAccumulate subPostAccumulate = newInstanceWithPrimaryKey(  ) ;
		if ( super.doSelect(subPostAccumulate) ) {
			return subPostAccumulate ;
		}
		else {
			return null ; // Not found
		}
	}
	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param subPostAccumulate
	 * @return true if found, false if not found
	 */
	@Override
	public boolean load( SubPostAccumulate subPostAccumulate ) {
		return super.doSelect(subPostAccumulate) ;
	}
    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param subPostAccumulate
	 */
	@Override
	public void insert(SubPostAccumulate subPostAccumulate) {
		super.doInsert(subPostAccumulate);
	}	

    //----------------------------------------------------------------------
	/**
	 * Updates the given bean in the database 
	 * @param subPostAccumulate
	 * @return
	 */
	@Override
	public int update(SubPostAccumulate subPostAccumulate) {
		return super.doUpdate(subPostAccumulate);
	}	

    //----------------------------------------------------------------------
	/**
	 * Deletes the record in the database using the given primary key value(s) 
	 * @return
	 */
	@Override
	public int delete(  ) {
		SubPostAccumulate subPostAccumulate = newInstanceWithPrimaryKey(  ) ;
		return super.doDelete(subPostAccumulate);
	}

    //----------------------------------------------------------------------
	/**
	 * Deletes the given bean in the database 
	 * @param subPostAccumulate
	 * @return
	 */
	@Override
	public int delete( SubPostAccumulate subPostAccumulate ) {
		return super.doDelete(subPostAccumulate);
	}

    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @return
	 */
	@Override
	public boolean exists(  ) {
		SubPostAccumulate subPostAccumulate = newInstanceWithPrimaryKey(  ) ;
		return super.doExists(subPostAccumulate);
	}
    //----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param subPostAccumulate
	 * @return
	 */
	@Override
	public boolean exists( SubPostAccumulate subPostAccumulate ) {
		return super.doExists(subPostAccumulate);
	}

    //----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database
	 * @return
	 */
	@Override
	public long count() {
		return super.doCountAll();
	}

    //----------------------------------------------------------------------
	@Override
	protected String getSqlSelect() {
		return SQL_SELECT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlInsert() {
		return SQL_INSERT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlUpdate() {
		return SQL_UPDATE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlDelete() {
		return SQL_DELETE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCount() {
		return SQL_COUNT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCountAll() {
		return SQL_COUNT_ALL ;
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForPrimaryKey(PreparedStatement ps, int i, SubPostAccumulate subPostAccumulate) throws SQLException {
		//--- Set PRIMARY KEY from bean to PreparedStatement ( SQL "WHERE key=?, ..." )
	}

    //----------------------------------------------------------------------
	@Override
	protected SubPostAccumulate populateBean(ResultSet rs, SubPostAccumulate subPostAccumulate) throws SQLException {

		//--- Set data from ResultSet to Bean attributes
		subPostAccumulate.setMsisdn(rs.getString("MSISDN")); // java.lang.String
		subPostAccumulate.setAccValue(rs.getBigDecimal("ACC_VALUE")); // java.math.BigDecimal
		if ( rs.wasNull() ) { subPostAccumulate.setAccValue(null); }; // not primitive number => keep null value if any
		subPostAccumulate.setLastAccValue(rs.getBigDecimal("LAST_ACC_VALUE")); // java.math.BigDecimal
		if ( rs.wasNull() ) { subPostAccumulate.setLastAccValue(null); }; // not primitive number => keep null value if any
		subPostAccumulate.setCodeCount(rs.getInt("CODE_COUNT")); // int
		subPostAccumulate.setLastCodeCount(rs.getInt("LAST_CODE_COUNT")); // int
		subPostAccumulate.setDateTime(rs.getDate("DATE_TIME")); // java.util.Date
		return subPostAccumulate ;
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForInsert(PreparedStatement ps, int i, SubPostAccumulate subPostAccumulate) throws SQLException {

		//--- Set PRIMARY KEY and DATA from bean to PreparedStatement ( SQL "SET x=?, y=?, ..." )
		setValue(ps, i++, subPostAccumulate.getMsisdn() ) ; // "MSISDN" : java.lang.String
		setValue(ps, i++, subPostAccumulate.getAccValue() ) ; // "ACC_VALUE" : java.math.BigDecimal
		setValue(ps, i++, subPostAccumulate.getLastAccValue() ) ; // "LAST_ACC_VALUE" : java.math.BigDecimal
		setValue(ps, i++, subPostAccumulate.getCodeCount() ) ; // "CODE_COUNT" : int
		setValue(ps, i++, subPostAccumulate.getLastCodeCount() ) ; // "LAST_CODE_COUNT" : int
		setValue(ps, i++, subPostAccumulate.getDateTime() ) ; // "DATE_TIME" : java.util.Date
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForUpdate(PreparedStatement ps, int i, SubPostAccumulate subPostAccumulate) throws SQLException {

		//--- Set DATA from bean to PreparedStatement ( SQL "SET x=?, y=?, ..." )
		setValue(ps, i++, subPostAccumulate.getMsisdn() ) ; // "MSISDN" : java.lang.String
		setValue(ps, i++, subPostAccumulate.getAccValue() ) ; // "ACC_VALUE" : java.math.BigDecimal
		setValue(ps, i++, subPostAccumulate.getLastAccValue() ) ; // "LAST_ACC_VALUE" : java.math.BigDecimal
		setValue(ps, i++, subPostAccumulate.getCodeCount() ) ; // "CODE_COUNT" : int
		setValue(ps, i++, subPostAccumulate.getLastCodeCount() ) ; // "LAST_CODE_COUNT" : int
		setValue(ps, i++, subPostAccumulate.getDateTime() ) ; // "DATE_TIME" : java.util.Date
		//--- Set PRIMARY KEY from bean to PreparedStatement ( SQL "WHERE key=?, ..." )
	}

}
