/*
 * Created on 17 Jun 2016 ( Time 12:35:41 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package vnp.dao.impl.jdbc;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import vnp.bean.SubsInLogs;
import vnp.dao.SubsInLogsDAO;
import vnp.dao.impl.jdbc.commons.GenericDAO;

/**
 * SubsInLogs DAO implementation 
 * 
 * @author Telosys Tools
 *
 */
public class SubsInLogsDAOImpl extends GenericDAO<SubsInLogs> implements SubsInLogsDAO {

	private final static String SQL_SELECT = 
		"select DATE_TIME, STATUS from SUBS_IN_LOGS where ";

	private final static String SQL_INSERT = 
		"insert into SUBS_IN_LOGS ( DATE_TIME, STATUS ) values ( ?, ? )";

	private final static String SQL_UPDATE = 
		"update SUBS_IN_LOGS set DATE_TIME = ?, STATUS = ? where ";

	private final static String SQL_DELETE = 
		"delete from SUBS_IN_LOGS where ";

	private final static String SQL_COUNT_ALL = 
		"select count(*) from SUBS_IN_LOGS";

	private final static String SQL_COUNT = 
		"select count(*) from SUBS_IN_LOGS where ";

    //----------------------------------------------------------------------
	/**
	 * DAO constructor
	 */
	public SubsInLogsDAOImpl() {
		super();
	}

	//----------------------------------------------------------------------
	/**
	 * Creates a new instance of the bean and populates it with the given primary value(s)
	 * @return the new instance
	 */
	private SubsInLogs newInstanceWithPrimaryKey(  ) {
		SubsInLogs subsInLogs = new SubsInLogs();
		return subsInLogs ;
	}

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @return the bean found or null if not found 
	 */
	@Override
	public SubsInLogs find(  ) {
		SubsInLogs subsInLogs = newInstanceWithPrimaryKey(  ) ;
		if ( super.doSelect(subsInLogs) ) {
			return subsInLogs ;
		}
		else {
			return null ; // Not found
		}
	}
	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param subsInLogs
	 * @return true if found, false if not found
	 */
	@Override
	public boolean load( SubsInLogs subsInLogs ) {
		return super.doSelect(subsInLogs) ;
	}
    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param subsInLogs
	 */
	@Override
	public void insert(SubsInLogs subsInLogs) {
		super.doInsert(subsInLogs);
	}	

    //----------------------------------------------------------------------
	/**
	 * Updates the given bean in the database 
	 * @param subsInLogs
	 * @return
	 */
	@Override
	public int update(SubsInLogs subsInLogs) {
		return super.doUpdate(subsInLogs);
	}	

    //----------------------------------------------------------------------
	/**
	 * Deletes the record in the database using the given primary key value(s) 
	 * @return
	 */
	@Override
	public int delete(  ) {
		SubsInLogs subsInLogs = newInstanceWithPrimaryKey(  ) ;
		return super.doDelete(subsInLogs);
	}

    //----------------------------------------------------------------------
	/**
	 * Deletes the given bean in the database 
	 * @param subsInLogs
	 * @return
	 */
	@Override
	public int delete( SubsInLogs subsInLogs ) {
		return super.doDelete(subsInLogs);
	}

    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @return
	 */
	@Override
	public boolean exists(  ) {
		SubsInLogs subsInLogs = newInstanceWithPrimaryKey(  ) ;
		return super.doExists(subsInLogs);
	}
    //----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param subsInLogs
	 * @return
	 */
	@Override
	public boolean exists( SubsInLogs subsInLogs ) {
		return super.doExists(subsInLogs);
	}

    //----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database
	 * @return
	 */
	@Override
	public long count() {
		return super.doCountAll();
	}

    //----------------------------------------------------------------------
	@Override
	protected String getSqlSelect() {
		return SQL_SELECT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlInsert() {
		return SQL_INSERT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlUpdate() {
		return SQL_UPDATE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlDelete() {
		return SQL_DELETE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCount() {
		return SQL_COUNT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCountAll() {
		return SQL_COUNT_ALL ;
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForPrimaryKey(PreparedStatement ps, int i, SubsInLogs subsInLogs) throws SQLException {
		//--- Set PRIMARY KEY from bean to PreparedStatement ( SQL "WHERE key=?, ..." )
	}

    //----------------------------------------------------------------------
	@Override
	protected SubsInLogs populateBean(ResultSet rs, SubsInLogs subsInLogs) throws SQLException {

		//--- Set data from ResultSet to Bean attributes
		subsInLogs.setDateTime(rs.getDate("DATE_TIME")); // java.util.Date
		subsInLogs.setStatus(rs.getInt("STATUS")); // int
		return subsInLogs ;
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForInsert(PreparedStatement ps, int i, SubsInLogs subsInLogs) throws SQLException {

		//--- Set PRIMARY KEY and DATA from bean to PreparedStatement ( SQL "SET x=?, y=?, ..." )
		setValue(ps, i++, subsInLogs.getDateTime() ) ; // "DATE_TIME" : java.util.Date
		setValue(ps, i++, subsInLogs.getStatus() ) ; // "STATUS" : int
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForUpdate(PreparedStatement ps, int i, SubsInLogs subsInLogs) throws SQLException {

		//--- Set DATA from bean to PreparedStatement ( SQL "SET x=?, y=?, ..." )
		setValue(ps, i++, subsInLogs.getDateTime() ) ; // "DATE_TIME" : java.util.Date
		setValue(ps, i++, subsInLogs.getStatus() ) ; // "STATUS" : int
		//--- Set PRIMARY KEY from bean to PreparedStatement ( SQL "WHERE key=?, ..." )
	}

}
