/*
 * Created on 17 Jun 2016 ( Time 12:35:41 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package vnp.dao.impl.jdbc;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import vnp.bean.SubsInDaily;
import vnp.dao.SubsInDailyDAO;
import vnp.dao.impl.jdbc.commons.GenericDAO;

/**
 * SubsInDaily DAO implementation 
 * 
 * @author Telosys Tools
 *
 */
public class SubsInDailyDAOImpl extends GenericDAO<SubsInDaily> implements SubsInDailyDAO {

	private final static String SQL_SELECT = 
		"select SUBSCRIBER_ID, TOTAL_TKC, DATE_TIME from SUBS_IN_DAILY where ";

	private final static String SQL_INSERT = 
		"insert into SUBS_IN_DAILY ( SUBSCRIBER_ID, TOTAL_TKC, DATE_TIME ) values ( ?, ?, ? )";

	private final static String SQL_UPDATE = 
		"update SUBS_IN_DAILY set SUBSCRIBER_ID = ?, TOTAL_TKC = ?, DATE_TIME = ? where ";

	private final static String SQL_DELETE = 
		"delete from SUBS_IN_DAILY where ";

	private final static String SQL_COUNT_ALL = 
		"select count(*) from SUBS_IN_DAILY";

	private final static String SQL_COUNT = 
		"select count(*) from SUBS_IN_DAILY where ";

    //----------------------------------------------------------------------
	/**
	 * DAO constructor
	 */
	public SubsInDailyDAOImpl() {
		super();
	}

	//----------------------------------------------------------------------
	/**
	 * Creates a new instance of the bean and populates it with the given primary value(s)
	 * @return the new instance
	 */
	private SubsInDaily newInstanceWithPrimaryKey(  ) {
		SubsInDaily subsInDaily = new SubsInDaily();
		return subsInDaily ;
	}

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @return the bean found or null if not found 
	 */
	@Override
	public SubsInDaily find(  ) {
		SubsInDaily subsInDaily = newInstanceWithPrimaryKey(  ) ;
		if ( super.doSelect(subsInDaily) ) {
			return subsInDaily ;
		}
		else {
			return null ; // Not found
		}
	}
	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param subsInDaily
	 * @return true if found, false if not found
	 */
	@Override
	public boolean load( SubsInDaily subsInDaily ) {
		return super.doSelect(subsInDaily) ;
	}
    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param subsInDaily
	 */
	@Override
	public void insert(SubsInDaily subsInDaily) {
		super.doInsert(subsInDaily);
	}	

    //----------------------------------------------------------------------
	/**
	 * Updates the given bean in the database 
	 * @param subsInDaily
	 * @return
	 */
	@Override
	public int update(SubsInDaily subsInDaily) {
		return super.doUpdate(subsInDaily);
	}	

    //----------------------------------------------------------------------
	/**
	 * Deletes the record in the database using the given primary key value(s) 
	 * @return
	 */
	@Override
	public int delete(  ) {
		SubsInDaily subsInDaily = newInstanceWithPrimaryKey(  ) ;
		return super.doDelete(subsInDaily);
	}

    //----------------------------------------------------------------------
	/**
	 * Deletes the given bean in the database 
	 * @param subsInDaily
	 * @return
	 */
	@Override
	public int delete( SubsInDaily subsInDaily ) {
		return super.doDelete(subsInDaily);
	}

    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @return
	 */
	@Override
	public boolean exists(  ) {
		SubsInDaily subsInDaily = newInstanceWithPrimaryKey(  ) ;
		return super.doExists(subsInDaily);
	}
    //----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param subsInDaily
	 * @return
	 */
	@Override
	public boolean exists( SubsInDaily subsInDaily ) {
		return super.doExists(subsInDaily);
	}

    //----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database
	 * @return
	 */
	@Override
	public long count() {
		return super.doCountAll();
	}

    //----------------------------------------------------------------------
	@Override
	protected String getSqlSelect() {
		return SQL_SELECT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlInsert() {
		return SQL_INSERT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlUpdate() {
		return SQL_UPDATE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlDelete() {
		return SQL_DELETE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCount() {
		return SQL_COUNT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCountAll() {
		return SQL_COUNT_ALL ;
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForPrimaryKey(PreparedStatement ps, int i, SubsInDaily subsInDaily) throws SQLException {
		//--- Set PRIMARY KEY from bean to PreparedStatement ( SQL "WHERE key=?, ..." )
	}

    //----------------------------------------------------------------------
	@Override
	protected SubsInDaily populateBean(ResultSet rs, SubsInDaily subsInDaily) throws SQLException {

		//--- Set data from ResultSet to Bean attributes
		subsInDaily.setSubscriberId(rs.getString("SUBSCRIBER_ID")); // java.lang.String
		subsInDaily.setTotalTkc(rs.getBigDecimal("TOTAL_TKC")); // java.math.BigDecimal
		if ( rs.wasNull() ) { subsInDaily.setTotalTkc(null); }; // not primitive number => keep null value if any
		subsInDaily.setDateTime(rs.getDate("DATE_TIME")); // java.util.Date
		return subsInDaily ;
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForInsert(PreparedStatement ps, int i, SubsInDaily subsInDaily) throws SQLException {

		//--- Set PRIMARY KEY and DATA from bean to PreparedStatement ( SQL "SET x=?, y=?, ..." )
		setValue(ps, i++, subsInDaily.getSubscriberId() ) ; // "SUBSCRIBER_ID" : java.lang.String
		setValue(ps, i++, subsInDaily.getTotalTkc() ) ; // "TOTAL_TKC" : java.math.BigDecimal
		setValue(ps, i++, subsInDaily.getDateTime() ) ; // "DATE_TIME" : java.util.Date
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForUpdate(PreparedStatement ps, int i, SubsInDaily subsInDaily) throws SQLException {

		//--- Set DATA from bean to PreparedStatement ( SQL "SET x=?, y=?, ..." )
		setValue(ps, i++, subsInDaily.getSubscriberId() ) ; // "SUBSCRIBER_ID" : java.lang.String
		setValue(ps, i++, subsInDaily.getTotalTkc() ) ; // "TOTAL_TKC" : java.math.BigDecimal
		setValue(ps, i++, subsInDaily.getDateTime() ) ; // "DATE_TIME" : java.util.Date
		//--- Set PRIMARY KEY from bean to PreparedStatement ( SQL "WHERE key=?, ..." )
	}

}
