/*
 * Created on 18 Nov 2016 ( Time 09:26:51 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package vnp.dao.impl.jdbc;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import vnp.bean.WinCampaign;
import vnp.dao.WinCampaignDAO;
import vnp.dao.impl.jdbc.commons.GenericDAO;

/**
 * WinCampaign DAO implementation 
 * 
 * @author Telosys Tools
 *
 */
public class WinCampaignDAOImpl extends GenericDAO<WinCampaign> implements WinCampaignDAO {

	private final static String SQL_SELECT = 
		"select SERVICE_ID, CAMPAIGN_ID, CAMPAIGN_NAME, START_TIME, FINISH_TIME, NOTES, ACTIVE, TYPE from WIN_CAMPAIGN where CAMPAIGN_ID = ?";

	private final static String SQL_INSERT = 
		"insert into WIN_CAMPAIGN ( SERVICE_ID, CAMPAIGN_ID, CAMPAIGN_NAME, START_TIME, FINISH_TIME, NOTES, ACTIVE, TYPE ) values ( ?, ?, ?, ?, ?, ?, ?, ? )";

	private final static String SQL_UPDATE = 
		"update WIN_CAMPAIGN set SERVICE_ID = ?, CAMPAIGN_NAME = ?, START_TIME = ?, FINISH_TIME = ?, NOTES = ?, ACTIVE = ?, TYPE = ? where CAMPAIGN_ID = ?";

	private final static String SQL_DELETE = 
		"delete from WIN_CAMPAIGN where CAMPAIGN_ID = ?";

	private final static String SQL_COUNT_ALL = 
		"select count(*) from WIN_CAMPAIGN";

	private final static String SQL_COUNT = 
		"select count(*) from WIN_CAMPAIGN where CAMPAIGN_ID = ?";

    //----------------------------------------------------------------------
	/**
	 * DAO constructor
	 */
	public WinCampaignDAOImpl() {
		super();
	}

	//----------------------------------------------------------------------
	/**
	 * Creates a new instance of the bean and populates it with the given primary value(s)
	 * @param campaignId;
	 * @return the new instance
	 */
	private WinCampaign newInstanceWithPrimaryKey( Long campaignId ) {
		WinCampaign winCampaign = new WinCampaign();
		winCampaign.setCampaignId( campaignId );
		return winCampaign ;
	}

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @param campaignId;
	 * @return the bean found or null if not found 
	 */
	@Override
	public WinCampaign find( Long campaignId ) {
		WinCampaign winCampaign = newInstanceWithPrimaryKey( campaignId ) ;
		if ( super.doSelect(winCampaign) ) {
			return winCampaign ;
		}
		else {
			return null ; // Not found
		}
	}
	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param winCampaign
	 * @return true if found, false if not found
	 */
	@Override
	public boolean load( WinCampaign winCampaign ) {
		return super.doSelect(winCampaign) ;
	}
    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param winCampaign
	 */
	@Override
	public void insert(WinCampaign winCampaign) {
		super.doInsert(winCampaign);
	}	

    //----------------------------------------------------------------------
	/**
	 * Updates the given bean in the database 
	 * @param winCampaign
	 * @return
	 */
	@Override
	public int update(WinCampaign winCampaign) {
		return super.doUpdate(winCampaign);
	}	

    //----------------------------------------------------------------------
	/**
	 * Deletes the record in the database using the given primary key value(s) 
	 * @param campaignId;
	 * @return
	 */
	@Override
	public int delete( Long campaignId ) {
		WinCampaign winCampaign = newInstanceWithPrimaryKey( campaignId ) ;
		return super.doDelete(winCampaign);
	}

    //----------------------------------------------------------------------
	/**
	 * Deletes the given bean in the database 
	 * @param winCampaign
	 * @return
	 */
	@Override
	public int delete( WinCampaign winCampaign ) {
		return super.doDelete(winCampaign);
	}

    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @param campaignId;
	 * @return
	 */
	@Override
	public boolean exists( Long campaignId ) {
		WinCampaign winCampaign = newInstanceWithPrimaryKey( campaignId ) ;
		return super.doExists(winCampaign);
	}
    //----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param winCampaign
	 * @return
	 */
	@Override
	public boolean exists( WinCampaign winCampaign ) {
		return super.doExists(winCampaign);
	}

    //----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database
	 * @return
	 */
	@Override
	public long count() {
		return super.doCountAll();
	}

    //----------------------------------------------------------------------
	@Override
	protected String getSqlSelect() {
		return SQL_SELECT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlInsert() {
		return SQL_INSERT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlUpdate() {
		return SQL_UPDATE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlDelete() {
		return SQL_DELETE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCount() {
		return SQL_COUNT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCountAll() {
		return SQL_COUNT_ALL ;
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForPrimaryKey(PreparedStatement ps, int i, WinCampaign winCampaign) throws SQLException {
		//--- Set PRIMARY KEY from bean to PreparedStatement ( SQL "WHERE key=?, ..." )
		setValue(ps, i++, winCampaign.getCampaignId() ) ; // "CAMPAIGN_ID" : java.lang.Long
	}

    //----------------------------------------------------------------------
	@Override
	protected WinCampaign populateBean(ResultSet rs, WinCampaign winCampaign) throws SQLException {

		//--- Set data from ResultSet to Bean attributes
		winCampaign.setServiceId(rs.getLong("SERVICE_ID")); // java.lang.Long
		if ( rs.wasNull() ) { winCampaign.setServiceId(null); }; // not primitive number => keep null value if any
		winCampaign.setCampaignId(rs.getLong("CAMPAIGN_ID")); // java.lang.Long
		if ( rs.wasNull() ) { winCampaign.setCampaignId(null); }; // not primitive number => keep null value if any
		winCampaign.setCampaignName(rs.getString("CAMPAIGN_NAME")); // java.lang.String
		winCampaign.setStartTime(rs.getDate("START_TIME")); // java.util.Date
		winCampaign.setFinishTime(rs.getDate("FINISH_TIME")); // java.util.Date
		winCampaign.setNotes(rs.getString("NOTES")); // java.lang.String
		winCampaign.setActive(rs.getInt("ACTIVE")); // java.lang.Integer
		if ( rs.wasNull() ) { winCampaign.setActive(null); }; // not primitive number => keep null value if any
		winCampaign.setType(rs.getString("TYPE")); // java.lang.String
		return winCampaign ;
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForInsert(PreparedStatement ps, int i, WinCampaign winCampaign) throws SQLException {

		//--- Set PRIMARY KEY and DATA from bean to PreparedStatement ( SQL "SET x=?, y=?, ..." )
		setValue(ps, i++, winCampaign.getServiceId() ) ; // "SERVICE_ID" : java.lang.Long
		setValue(ps, i++, winCampaign.getCampaignId() ) ; // "CAMPAIGN_ID" : java.lang.Long
		setValue(ps, i++, winCampaign.getCampaignName() ) ; // "CAMPAIGN_NAME" : java.lang.String
		setValue(ps, i++, winCampaign.getStartTime() ) ; // "START_TIME" : java.util.Date
		setValue(ps, i++, winCampaign.getFinishTime() ) ; // "FINISH_TIME" : java.util.Date
		setValue(ps, i++, winCampaign.getNotes() ) ; // "NOTES" : java.lang.String
		setValue(ps, i++, winCampaign.getActive() ) ; // "ACTIVE" : java.lang.Integer
		setValue(ps, i++, winCampaign.getType() ) ; // "TYPE" : java.lang.String
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForUpdate(PreparedStatement ps, int i, WinCampaign winCampaign) throws SQLException {

		//--- Set DATA from bean to PreparedStatement ( SQL "SET x=?, y=?, ..." )
		setValue(ps, i++, winCampaign.getServiceId() ) ; // "SERVICE_ID" : java.lang.Long
		setValue(ps, i++, winCampaign.getCampaignName() ) ; // "CAMPAIGN_NAME" : java.lang.String
		setValue(ps, i++, winCampaign.getStartTime() ) ; // "START_TIME" : java.util.Date
		setValue(ps, i++, winCampaign.getFinishTime() ) ; // "FINISH_TIME" : java.util.Date
		setValue(ps, i++, winCampaign.getNotes() ) ; // "NOTES" : java.lang.String
		setValue(ps, i++, winCampaign.getActive() ) ; // "ACTIVE" : java.lang.Integer
		setValue(ps, i++, winCampaign.getType() ) ; // "TYPE" : java.lang.String
		//--- Set PRIMARY KEY from bean to PreparedStatement ( SQL "WHERE key=?, ..." )
		setValue(ps, i++, winCampaign.getCampaignId() ) ; // "CAMPAIGN_ID" : java.lang.Long
	}

}
