/*
 * Created on 18 Nov 2016 ( Time 09:26:51 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package vnp.dao.impl.jdbc;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import vnp.bean.WinConfig;
import vnp.dao.WinConfigDAO;
import vnp.dao.impl.jdbc.commons.GenericDAO;

/**
 * WinConfig DAO implementation 
 * 
 * @author Telosys Tools
 *
 */
public class WinConfigDAOImpl extends GenericDAO<WinConfig> implements WinConfigDAO {

	private final static String SQL_SELECT = 
		"select CAMPAIGN_ID, CONFIG_KEY, CONFIG_VALUE, CONFIG_TYPE from WIN_CONFIG where CAMPAIGN_ID = ? and CONFIG_KEY = ?";

	private final static String SQL_INSERT = 
		"insert into WIN_CONFIG ( CAMPAIGN_ID, CONFIG_KEY, CONFIG_VALUE, CONFIG_TYPE ) values ( ?, ?, ?, ? )";

	private final static String SQL_UPDATE = 
		"update WIN_CONFIG set CONFIG_VALUE = ?, CONFIG_TYPE = ? where CAMPAIGN_ID = ? and CONFIG_KEY = ?";

	private final static String SQL_DELETE = 
		"delete from WIN_CONFIG where CAMPAIGN_ID = ? and CONFIG_KEY = ?";

	private final static String SQL_COUNT_ALL = 
		"select count(*) from WIN_CONFIG";

	private final static String SQL_COUNT = 
		"select count(*) from WIN_CONFIG where CAMPAIGN_ID = ? and CONFIG_KEY = ?";

    //----------------------------------------------------------------------
	/**
	 * DAO constructor
	 */
	public WinConfigDAOImpl() {
		super();
	}

	//----------------------------------------------------------------------
	/**
	 * Creates a new instance of the bean and populates it with the given primary value(s)
	 * @param campaignId;
	 * @param configKey;
	 * @return the new instance
	 */
	private WinConfig newInstanceWithPrimaryKey( Long campaignId, String configKey ) {
		WinConfig winConfig = new WinConfig();
		winConfig.setCampaignId( campaignId );
		winConfig.setConfigKey( configKey );
		return winConfig ;
	}

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @param campaignId;
	 * @param configKey;
	 * @return the bean found or null if not found 
	 */
	@Override
	public WinConfig find( Long campaignId, String configKey ) {
		WinConfig winConfig = newInstanceWithPrimaryKey( campaignId, configKey ) ;
		if ( super.doSelect(winConfig) ) {
			return winConfig ;
		}
		else {
			return null ; // Not found
		}
	}
	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param winConfig
	 * @return true if found, false if not found
	 */
	@Override
	public boolean load( WinConfig winConfig ) {
		return super.doSelect(winConfig) ;
	}
    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param winConfig
	 */
	@Override
	public void insert(WinConfig winConfig) {
		super.doInsert(winConfig);
	}	

    //----------------------------------------------------------------------
	/**
	 * Updates the given bean in the database 
	 * @param winConfig
	 * @return
	 */
	@Override
	public int update(WinConfig winConfig) {
		return super.doUpdate(winConfig);
	}	

    //----------------------------------------------------------------------
	/**
	 * Deletes the record in the database using the given primary key value(s) 
	 * @param campaignId;
	 * @param configKey;
	 * @return
	 */
	@Override
	public int delete( Long campaignId, String configKey ) {
		WinConfig winConfig = newInstanceWithPrimaryKey( campaignId, configKey ) ;
		return super.doDelete(winConfig);
	}

    //----------------------------------------------------------------------
	/**
	 * Deletes the given bean in the database 
	 * @param winConfig
	 * @return
	 */
	@Override
	public int delete( WinConfig winConfig ) {
		return super.doDelete(winConfig);
	}

    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @param campaignId;
	 * @param configKey;
	 * @return
	 */
	@Override
	public boolean exists( Long campaignId, String configKey ) {
		WinConfig winConfig = newInstanceWithPrimaryKey( campaignId, configKey ) ;
		return super.doExists(winConfig);
	}
    //----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param winConfig
	 * @return
	 */
	@Override
	public boolean exists( WinConfig winConfig ) {
		return super.doExists(winConfig);
	}

    //----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database
	 * @return
	 */
	@Override
	public long count() {
		return super.doCountAll();
	}

    //----------------------------------------------------------------------
	@Override
	protected String getSqlSelect() {
		return SQL_SELECT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlInsert() {
		return SQL_INSERT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlUpdate() {
		return SQL_UPDATE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlDelete() {
		return SQL_DELETE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCount() {
		return SQL_COUNT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCountAll() {
		return SQL_COUNT_ALL ;
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForPrimaryKey(PreparedStatement ps, int i, WinConfig winConfig) throws SQLException {
		//--- Set PRIMARY KEY from bean to PreparedStatement ( SQL "WHERE key=?, ..." )
		setValue(ps, i++, winConfig.getCampaignId() ) ; // "CAMPAIGN_ID" : java.lang.Long
		setValue(ps, i++, winConfig.getConfigKey() ) ; // "CONFIG_KEY" : java.lang.String
	}

    //----------------------------------------------------------------------
	@Override
	protected WinConfig populateBean(ResultSet rs, WinConfig winConfig) throws SQLException {

		//--- Set data from ResultSet to Bean attributes
		winConfig.setCampaignId(rs.getLong("CAMPAIGN_ID")); // java.lang.Long
		if ( rs.wasNull() ) { winConfig.setCampaignId(null); }; // not primitive number => keep null value if any
		winConfig.setConfigKey(rs.getString("CONFIG_KEY")); // java.lang.String
		winConfig.setConfigValue(rs.getString("CONFIG_VALUE")); // java.lang.String
		winConfig.setConfigType(rs.getString("CONFIG_TYPE")); // java.lang.String
		return winConfig ;
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForInsert(PreparedStatement ps, int i, WinConfig winConfig) throws SQLException {

		//--- Set PRIMARY KEY and DATA from bean to PreparedStatement ( SQL "SET x=?, y=?, ..." )
		setValue(ps, i++, winConfig.getCampaignId() ) ; // "CAMPAIGN_ID" : java.lang.Long
		setValue(ps, i++, winConfig.getConfigKey() ) ; // "CONFIG_KEY" : java.lang.String
		setValue(ps, i++, winConfig.getConfigValue() ) ; // "CONFIG_VALUE" : java.lang.String
		setValue(ps, i++, winConfig.getConfigType() ) ; // "CONFIG_TYPE" : java.lang.String
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForUpdate(PreparedStatement ps, int i, WinConfig winConfig) throws SQLException {

		//--- Set DATA from bean to PreparedStatement ( SQL "SET x=?, y=?, ..." )
		setValue(ps, i++, winConfig.getConfigValue() ) ; // "CONFIG_VALUE" : java.lang.String
		setValue(ps, i++, winConfig.getConfigType() ) ; // "CONFIG_TYPE" : java.lang.String
		//--- Set PRIMARY KEY from bean to PreparedStatement ( SQL "WHERE key=?, ..." )
		setValue(ps, i++, winConfig.getCampaignId() ) ; // "CAMPAIGN_ID" : java.lang.Long
		setValue(ps, i++, winConfig.getConfigKey() ) ; // "CONFIG_KEY" : java.lang.String
	}

}
