/*
 * Created on 18 Nov 2016 ( Time 09:26:51 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package vnp.dao.impl.jdbc;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import vnp.bean.WinMtLog;
import vnp.dao.WinMtLogDAO;
import vnp.dao.impl.jdbc.commons.GenericDAO;

/**
 * WinMtLog DAO implementation 
 * 
 * @author Telosys Tools
 *
 */
public class WinMtLogDAOImpl extends GenericDAO<WinMtLog> implements WinMtLogDAO {

	private final static String SQL_SELECT = 
		"select CAMPAIGN_ID, MSISDN, MT_CONTENT, STATUS, SENT_TIME from WIN_MT_LOG where ";

	private final static String SQL_INSERT = 
		"insert into WIN_MT_LOG ( CAMPAIGN_ID, MSISDN, MT_CONTENT, STATUS, SENT_TIME ) values ( ?, ?, ?, ?, ? )";

	private final static String SQL_UPDATE = 
		"update WIN_MT_LOG set CAMPAIGN_ID = ?, MSISDN = ?, MT_CONTENT = ?, STATUS = ?, SENT_TIME = ? where ";

	private final static String SQL_DELETE = 
		"delete from WIN_MT_LOG where ";

	private final static String SQL_COUNT_ALL = 
		"select count(*) from WIN_MT_LOG";

	private final static String SQL_COUNT = 
		"select count(*) from WIN_MT_LOG where ";

    //----------------------------------------------------------------------
	/**
	 * DAO constructor
	 */
	public WinMtLogDAOImpl() {
		super();
	}

	//----------------------------------------------------------------------
	/**
	 * Creates a new instance of the bean and populates it with the given primary value(s)
	 * @return the new instance
	 */
	private WinMtLog newInstanceWithPrimaryKey(  ) {
		WinMtLog winMtLog = new WinMtLog();
		return winMtLog ;
	}

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @return the bean found or null if not found 
	 */
	@Override
	public WinMtLog find(  ) {
		WinMtLog winMtLog = newInstanceWithPrimaryKey(  ) ;
		if ( super.doSelect(winMtLog) ) {
			return winMtLog ;
		}
		else {
			return null ; // Not found
		}
	}
	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param winMtLog
	 * @return true if found, false if not found
	 */
	@Override
	public boolean load( WinMtLog winMtLog ) {
		return super.doSelect(winMtLog) ;
	}
    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param winMtLog
	 */
	@Override
	public void insert(WinMtLog winMtLog) {
		super.doInsert(winMtLog);
	}	

    //----------------------------------------------------------------------
	/**
	 * Updates the given bean in the database 
	 * @param winMtLog
	 * @return
	 */
	@Override
	public int update(WinMtLog winMtLog) {
		return super.doUpdate(winMtLog);
	}	

    //----------------------------------------------------------------------
	/**
	 * Deletes the record in the database using the given primary key value(s) 
	 * @return
	 */
	@Override
	public int delete(  ) {
		WinMtLog winMtLog = newInstanceWithPrimaryKey(  ) ;
		return super.doDelete(winMtLog);
	}

    //----------------------------------------------------------------------
	/**
	 * Deletes the given bean in the database 
	 * @param winMtLog
	 * @return
	 */
	@Override
	public int delete( WinMtLog winMtLog ) {
		return super.doDelete(winMtLog);
	}

    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @return
	 */
	@Override
	public boolean exists(  ) {
		WinMtLog winMtLog = newInstanceWithPrimaryKey(  ) ;
		return super.doExists(winMtLog);
	}
    //----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param winMtLog
	 * @return
	 */
	@Override
	public boolean exists( WinMtLog winMtLog ) {
		return super.doExists(winMtLog);
	}

    //----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database
	 * @return
	 */
	@Override
	public long count() {
		return super.doCountAll();
	}

    //----------------------------------------------------------------------
	@Override
	protected String getSqlSelect() {
		return SQL_SELECT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlInsert() {
		return SQL_INSERT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlUpdate() {
		return SQL_UPDATE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlDelete() {
		return SQL_DELETE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCount() {
		return SQL_COUNT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCountAll() {
		return SQL_COUNT_ALL ;
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForPrimaryKey(PreparedStatement ps, int i, WinMtLog winMtLog) throws SQLException {
		//--- Set PRIMARY KEY from bean to PreparedStatement ( SQL "WHERE key=?, ..." )
	}

    //----------------------------------------------------------------------
	@Override
	protected WinMtLog populateBean(ResultSet rs, WinMtLog winMtLog) throws SQLException {

		//--- Set data from ResultSet to Bean attributes
		winMtLog.setCampaignId(rs.getLong("CAMPAIGN_ID")); // java.lang.Long
		if ( rs.wasNull() ) { winMtLog.setCampaignId(null); }; // not primitive number => keep null value if any
		winMtLog.setMsisdn(rs.getString("MSISDN")); // java.lang.String
		winMtLog.setMtContent(rs.getString("MT_CONTENT")); // java.lang.String
		winMtLog.setStatus(rs.getInt("STATUS")); // java.lang.Integer
		if ( rs.wasNull() ) { winMtLog.setStatus(null); }; // not primitive number => keep null value if any
		winMtLog.setSentTime(rs.getDate("SENT_TIME")); // java.util.Date
		return winMtLog ;
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForInsert(PreparedStatement ps, int i, WinMtLog winMtLog) throws SQLException {

		//--- Set PRIMARY KEY and DATA from bean to PreparedStatement ( SQL "SET x=?, y=?, ..." )
		setValue(ps, i++, winMtLog.getCampaignId() ) ; // "CAMPAIGN_ID" : java.lang.Long
		setValue(ps, i++, winMtLog.getMsisdn() ) ; // "MSISDN" : java.lang.String
		setValue(ps, i++, winMtLog.getMtContent() ) ; // "MT_CONTENT" : java.lang.String
		setValue(ps, i++, winMtLog.getStatus() ) ; // "STATUS" : java.lang.Integer
		setValue(ps, i++, winMtLog.getSentTime() ) ; // "SENT_TIME" : java.util.Date
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForUpdate(PreparedStatement ps, int i, WinMtLog winMtLog) throws SQLException {

		//--- Set DATA from bean to PreparedStatement ( SQL "SET x=?, y=?, ..." )
		setValue(ps, i++, winMtLog.getCampaignId() ) ; // "CAMPAIGN_ID" : java.lang.Long
		setValue(ps, i++, winMtLog.getMsisdn() ) ; // "MSISDN" : java.lang.String
		setValue(ps, i++, winMtLog.getMtContent() ) ; // "MT_CONTENT" : java.lang.String
		setValue(ps, i++, winMtLog.getStatus() ) ; // "STATUS" : java.lang.Integer
		setValue(ps, i++, winMtLog.getSentTime() ) ; // "SENT_TIME" : java.util.Date
		//--- Set PRIMARY KEY from bean to PreparedStatement ( SQL "WHERE key=?, ..." )
	}

}
