/*
 * Created on 18 Nov 2016 ( Time 09:26:51 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package vnp.dao.impl.jdbc;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import vnp.bean.WinMtTemplate;
import vnp.dao.WinMtTemplateDAO;
import vnp.dao.impl.jdbc.commons.GenericDAO;

/**
 * WinMtTemplate DAO implementation 
 * 
 * @author Telosys Tools
 *
 */
public class WinMtTemplateDAOImpl extends GenericDAO<WinMtTemplate> implements WinMtTemplateDAO {

	private final static String SQL_SELECT = 
		"select CAMPAIGN_ID, MT_CODE, MT_CONTENT from WIN_MT_TEMPLATE where CAMPAIGN_ID = ? and MT_CODE = ?";

	private final static String SQL_INSERT = 
		"insert into WIN_MT_TEMPLATE ( CAMPAIGN_ID, MT_CODE, MT_CONTENT ) values ( ?, ?, ? )";

	private final static String SQL_UPDATE = 
		"update WIN_MT_TEMPLATE set MT_CONTENT = ? where CAMPAIGN_ID = ? and MT_CODE = ?";

	private final static String SQL_DELETE = 
		"delete from WIN_MT_TEMPLATE where CAMPAIGN_ID = ? and MT_CODE = ?";

	private final static String SQL_COUNT_ALL = 
		"select count(*) from WIN_MT_TEMPLATE";

	private final static String SQL_COUNT = 
		"select count(*) from WIN_MT_TEMPLATE where CAMPAIGN_ID = ? and MT_CODE = ?";

    //----------------------------------------------------------------------
	/**
	 * DAO constructor
	 */
	public WinMtTemplateDAOImpl() {
		super();
	}

	//----------------------------------------------------------------------
	/**
	 * Creates a new instance of the bean and populates it with the given primary value(s)
	 * @param campaignId;
	 * @param mtCode;
	 * @return the new instance
	 */
	private WinMtTemplate newInstanceWithPrimaryKey( Long campaignId, String mtCode ) {
		WinMtTemplate winMtTemplate = new WinMtTemplate();
		winMtTemplate.setCampaignId( campaignId );
		winMtTemplate.setMtCode( mtCode );
		return winMtTemplate ;
	}

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @param campaignId;
	 * @param mtCode;
	 * @return the bean found or null if not found 
	 */
	@Override
	public WinMtTemplate find( Long campaignId, String mtCode ) {
		WinMtTemplate winMtTemplate = newInstanceWithPrimaryKey( campaignId, mtCode ) ;
		if ( super.doSelect(winMtTemplate) ) {
			return winMtTemplate ;
		}
		else {
			return null ; // Not found
		}
	}
	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param winMtTemplate
	 * @return true if found, false if not found
	 */
	@Override
	public boolean load( WinMtTemplate winMtTemplate ) {
		return super.doSelect(winMtTemplate) ;
	}
    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param winMtTemplate
	 */
	@Override
	public void insert(WinMtTemplate winMtTemplate) {
		super.doInsert(winMtTemplate);
	}	

    //----------------------------------------------------------------------
	/**
	 * Updates the given bean in the database 
	 * @param winMtTemplate
	 * @return
	 */
	@Override
	public int update(WinMtTemplate winMtTemplate) {
		return super.doUpdate(winMtTemplate);
	}	

    //----------------------------------------------------------------------
	/**
	 * Deletes the record in the database using the given primary key value(s) 
	 * @param campaignId;
	 * @param mtCode;
	 * @return
	 */
	@Override
	public int delete( Long campaignId, String mtCode ) {
		WinMtTemplate winMtTemplate = newInstanceWithPrimaryKey( campaignId, mtCode ) ;
		return super.doDelete(winMtTemplate);
	}

    //----------------------------------------------------------------------
	/**
	 * Deletes the given bean in the database 
	 * @param winMtTemplate
	 * @return
	 */
	@Override
	public int delete( WinMtTemplate winMtTemplate ) {
		return super.doDelete(winMtTemplate);
	}

    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @param campaignId;
	 * @param mtCode;
	 * @return
	 */
	@Override
	public boolean exists( Long campaignId, String mtCode ) {
		WinMtTemplate winMtTemplate = newInstanceWithPrimaryKey( campaignId, mtCode ) ;
		return super.doExists(winMtTemplate);
	}
    //----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param winMtTemplate
	 * @return
	 */
	@Override
	public boolean exists( WinMtTemplate winMtTemplate ) {
		return super.doExists(winMtTemplate);
	}

    //----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database
	 * @return
	 */
	@Override
	public long count() {
		return super.doCountAll();
	}

    //----------------------------------------------------------------------
	@Override
	protected String getSqlSelect() {
		return SQL_SELECT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlInsert() {
		return SQL_INSERT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlUpdate() {
		return SQL_UPDATE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlDelete() {
		return SQL_DELETE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCount() {
		return SQL_COUNT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCountAll() {
		return SQL_COUNT_ALL ;
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForPrimaryKey(PreparedStatement ps, int i, WinMtTemplate winMtTemplate) throws SQLException {
		//--- Set PRIMARY KEY from bean to PreparedStatement ( SQL "WHERE key=?, ..." )
		setValue(ps, i++, winMtTemplate.getCampaignId() ) ; // "CAMPAIGN_ID" : java.lang.Long
		setValue(ps, i++, winMtTemplate.getMtCode() ) ; // "MT_CODE" : java.lang.String
	}

    //----------------------------------------------------------------------
	@Override
	protected WinMtTemplate populateBean(ResultSet rs, WinMtTemplate winMtTemplate) throws SQLException {

		//--- Set data from ResultSet to Bean attributes
		winMtTemplate.setCampaignId(rs.getLong("CAMPAIGN_ID")); // java.lang.Long
		if ( rs.wasNull() ) { winMtTemplate.setCampaignId(null); }; // not primitive number => keep null value if any
		winMtTemplate.setMtCode(rs.getString("MT_CODE")); // java.lang.String
		winMtTemplate.setMtContent(rs.getString("MT_CONTENT")); // java.lang.String
		return winMtTemplate ;
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForInsert(PreparedStatement ps, int i, WinMtTemplate winMtTemplate) throws SQLException {

		//--- Set PRIMARY KEY and DATA from bean to PreparedStatement ( SQL "SET x=?, y=?, ..." )
		setValue(ps, i++, winMtTemplate.getCampaignId() ) ; // "CAMPAIGN_ID" : java.lang.Long
		setValue(ps, i++, winMtTemplate.getMtCode() ) ; // "MT_CODE" : java.lang.String
		setValue(ps, i++, winMtTemplate.getMtContent() ) ; // "MT_CONTENT" : java.lang.String
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForUpdate(PreparedStatement ps, int i, WinMtTemplate winMtTemplate) throws SQLException {

		//--- Set DATA from bean to PreparedStatement ( SQL "SET x=?, y=?, ..." )
		setValue(ps, i++, winMtTemplate.getMtContent() ) ; // "MT_CONTENT" : java.lang.String
		//--- Set PRIMARY KEY from bean to PreparedStatement ( SQL "WHERE key=?, ..." )
		setValue(ps, i++, winMtTemplate.getCampaignId() ) ; // "CAMPAIGN_ID" : java.lang.Long
		setValue(ps, i++, winMtTemplate.getMtCode() ) ; // "MT_CODE" : java.lang.String
	}

}
