/*
 * Created on 18 Nov 2016 ( Time 09:26:51 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package vnp.dao.impl.jdbc;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import vnp.bean.WinPrizes;
import vnp.dao.WinPrizesDAO;
import vnp.dao.impl.jdbc.commons.GenericDAO;

/**
 * WinPrizes DAO implementation 
 * 
 * @author Telosys Tools
 *
 */
public class WinPrizesDAOImpl extends GenericDAO<WinPrizes> implements WinPrizesDAO {

	private final static String SQL_SELECT = 
		"select CAMPAIGN_ID, PRIZE_LEVEL, PRIZE_NAME, PRIZE_DESCRIPTION, PRIZE_PRICE, PRIZE_TOTAL, AUTOPAYMENT, PRIZE_DAYS from WIN_PRIZES where CAMPAIGN_ID = ? and PRIZE_LEVEL = ?";

	private final static String SQL_INSERT = 
		"insert into WIN_PRIZES ( CAMPAIGN_ID, PRIZE_LEVEL, PRIZE_NAME, PRIZE_DESCRIPTION, PRIZE_PRICE, PRIZE_TOTAL, AUTOPAYMENT, PRIZE_DAYS ) values ( ?, ?, ?, ?, ?, ?, ?, ? )";

	private final static String SQL_UPDATE = 
		"update WIN_PRIZES set PRIZE_NAME = ?, PRIZE_DESCRIPTION = ?, PRIZE_PRICE = ?, PRIZE_TOTAL = ?, AUTOPAYMENT = ?, PRIZE_DAYS = ? where CAMPAIGN_ID = ? and PRIZE_LEVEL = ?";

	private final static String SQL_DELETE = 
		"delete from WIN_PRIZES where CAMPAIGN_ID = ? and PRIZE_LEVEL = ?";

	private final static String SQL_COUNT_ALL = 
		"select count(*) from WIN_PRIZES";

	private final static String SQL_COUNT = 
		"select count(*) from WIN_PRIZES where CAMPAIGN_ID = ? and PRIZE_LEVEL = ?";

    //----------------------------------------------------------------------
	/**
	 * DAO constructor
	 */
	public WinPrizesDAOImpl() {
		super();
	}

	//----------------------------------------------------------------------
	/**
	 * Creates a new instance of the bean and populates it with the given primary value(s)
	 * @param campaignId;
	 * @param prizeLevel;
	 * @return the new instance
	 */
	private WinPrizes newInstanceWithPrimaryKey( Long campaignId, Long prizeLevel ) {
		WinPrizes winPrizes = new WinPrizes();
		winPrizes.setCampaignId( campaignId );
		winPrizes.setPrizeLevel( prizeLevel );
		return winPrizes ;
	}

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @param campaignId;
	 * @param prizeLevel;
	 * @return the bean found or null if not found 
	 */
	@Override
	public WinPrizes find( Long campaignId, Long prizeLevel ) {
		WinPrizes winPrizes = newInstanceWithPrimaryKey( campaignId, prizeLevel ) ;
		if ( super.doSelect(winPrizes) ) {
			return winPrizes ;
		}
		else {
			return null ; // Not found
		}
	}
	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param winPrizes
	 * @return true if found, false if not found
	 */
	@Override
	public boolean load( WinPrizes winPrizes ) {
		return super.doSelect(winPrizes) ;
	}
    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param winPrizes
	 */
	@Override
	public void insert(WinPrizes winPrizes) {
		super.doInsert(winPrizes);
	}	

    //----------------------------------------------------------------------
	/**
	 * Updates the given bean in the database 
	 * @param winPrizes
	 * @return
	 */
	@Override
	public int update(WinPrizes winPrizes) {
		return super.doUpdate(winPrizes);
	}	

    //----------------------------------------------------------------------
	/**
	 * Deletes the record in the database using the given primary key value(s) 
	 * @param campaignId;
	 * @param prizeLevel;
	 * @return
	 */
	@Override
	public int delete( Long campaignId, Long prizeLevel ) {
		WinPrizes winPrizes = newInstanceWithPrimaryKey( campaignId, prizeLevel ) ;
		return super.doDelete(winPrizes);
	}

    //----------------------------------------------------------------------
	/**
	 * Deletes the given bean in the database 
	 * @param winPrizes
	 * @return
	 */
	@Override
	public int delete( WinPrizes winPrizes ) {
		return super.doDelete(winPrizes);
	}

    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @param campaignId;
	 * @param prizeLevel;
	 * @return
	 */
	@Override
	public boolean exists( Long campaignId, Long prizeLevel ) {
		WinPrizes winPrizes = newInstanceWithPrimaryKey( campaignId, prizeLevel ) ;
		return super.doExists(winPrizes);
	}
    //----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param winPrizes
	 * @return
	 */
	@Override
	public boolean exists( WinPrizes winPrizes ) {
		return super.doExists(winPrizes);
	}

    //----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database
	 * @return
	 */
	@Override
	public long count() {
		return super.doCountAll();
	}

    //----------------------------------------------------------------------
	@Override
	protected String getSqlSelect() {
		return SQL_SELECT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlInsert() {
		return SQL_INSERT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlUpdate() {
		return SQL_UPDATE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlDelete() {
		return SQL_DELETE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCount() {
		return SQL_COUNT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCountAll() {
		return SQL_COUNT_ALL ;
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForPrimaryKey(PreparedStatement ps, int i, WinPrizes winPrizes) throws SQLException {
		//--- Set PRIMARY KEY from bean to PreparedStatement ( SQL "WHERE key=?, ..." )
		setValue(ps, i++, winPrizes.getCampaignId() ) ; // "CAMPAIGN_ID" : java.lang.Long
		setValue(ps, i++, winPrizes.getPrizeLevel() ) ; // "PRIZE_LEVEL" : java.lang.Long
	}

    //----------------------------------------------------------------------
	@Override
	protected WinPrizes populateBean(ResultSet rs, WinPrizes winPrizes) throws SQLException {

		//--- Set data from ResultSet to Bean attributes
		winPrizes.setCampaignId(rs.getLong("CAMPAIGN_ID")); // java.lang.Long
		if ( rs.wasNull() ) { winPrizes.setCampaignId(null); }; // not primitive number => keep null value if any
		winPrizes.setPrizeLevel(rs.getLong("PRIZE_LEVEL")); // java.lang.Long
		if ( rs.wasNull() ) { winPrizes.setPrizeLevel(null); }; // not primitive number => keep null value if any
		winPrizes.setPrizeName(rs.getString("PRIZE_NAME")); // java.lang.String
		winPrizes.setPrizeDescription(rs.getString("PRIZE_DESCRIPTION")); // java.lang.String
		winPrizes.setPrizePrice(rs.getBigDecimal("PRIZE_PRICE")); // java.math.BigDecimal
		if ( rs.wasNull() ) { winPrizes.setPrizePrice(null); }; // not primitive number => keep null value if any
		winPrizes.setPrizeTotal(rs.getInt("PRIZE_TOTAL")); // java.lang.Integer
		if ( rs.wasNull() ) { winPrizes.setPrizeTotal(null); }; // not primitive number => keep null value if any
		winPrizes.setAutopayment(rs.getInt("AUTOPAYMENT")); // java.lang.Integer
		if ( rs.wasNull() ) { winPrizes.setAutopayment(null); }; // not primitive number => keep null value if any
		winPrizes.setPrizeDays(rs.getInt("PRIZE_DAYS")); // java.lang.Integer
		if ( rs.wasNull() ) { winPrizes.setPrizeDays(null); }; // not primitive number => keep null value if any
		return winPrizes ;
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForInsert(PreparedStatement ps, int i, WinPrizes winPrizes) throws SQLException {

		//--- Set PRIMARY KEY and DATA from bean to PreparedStatement ( SQL "SET x=?, y=?, ..." )
		setValue(ps, i++, winPrizes.getCampaignId() ) ; // "CAMPAIGN_ID" : java.lang.Long
		setValue(ps, i++, winPrizes.getPrizeLevel() ) ; // "PRIZE_LEVEL" : java.lang.Long
		setValue(ps, i++, winPrizes.getPrizeName() ) ; // "PRIZE_NAME" : java.lang.String
		setValue(ps, i++, winPrizes.getPrizeDescription() ) ; // "PRIZE_DESCRIPTION" : java.lang.String
		setValue(ps, i++, winPrizes.getPrizePrice() ) ; // "PRIZE_PRICE" : java.math.BigDecimal
		setValue(ps, i++, winPrizes.getPrizeTotal() ) ; // "PRIZE_TOTAL" : java.lang.Integer
		setValue(ps, i++, winPrizes.getAutopayment() ) ; // "AUTOPAYMENT" : java.lang.Integer
		setValue(ps, i++, winPrizes.getPrizeDays() ) ; // "PRIZE_DAYS" : java.lang.Integer
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForUpdate(PreparedStatement ps, int i, WinPrizes winPrizes) throws SQLException {

		//--- Set DATA from bean to PreparedStatement ( SQL "SET x=?, y=?, ..." )
		setValue(ps, i++, winPrizes.getPrizeName() ) ; // "PRIZE_NAME" : java.lang.String
		setValue(ps, i++, winPrizes.getPrizeDescription() ) ; // "PRIZE_DESCRIPTION" : java.lang.String
		setValue(ps, i++, winPrizes.getPrizePrice() ) ; // "PRIZE_PRICE" : java.math.BigDecimal
		setValue(ps, i++, winPrizes.getPrizeTotal() ) ; // "PRIZE_TOTAL" : java.lang.Integer
		setValue(ps, i++, winPrizes.getAutopayment() ) ; // "AUTOPAYMENT" : java.lang.Integer
		setValue(ps, i++, winPrizes.getPrizeDays() ) ; // "PRIZE_DAYS" : java.lang.Integer
		//--- Set PRIMARY KEY from bean to PreparedStatement ( SQL "WHERE key=?, ..." )
		setValue(ps, i++, winPrizes.getCampaignId() ) ; // "CAMPAIGN_ID" : java.lang.Long
		setValue(ps, i++, winPrizes.getPrizeLevel() ) ; // "PRIZE_LEVEL" : java.lang.Long
	}

}
