/*
 * Created on 2 Jun 2016 ( Time 17:03:56 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package vnp.bean;

import java.io.Serializable;

import java.math.BigDecimal;
import java.util.Date;

/**
 * Java bean for 'IsdnAll' entity
 * 
 * @author Telosys Tools
 *
 */
public class IsdnAll implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // DB : ISDN VARCHAR2 
    private String isdn;

    // DB : NO_CODE NUMBER 
    private BigDecimal noCode;

    // DB : DATE_ACTIVE DATE 
    private Date dateActive;

    // DB : DATE_IMPORT DATE 
    private Date dateImport;

    // DB : SUBTYPE VARCHAR2 
    private String subtype;

    // DB : SERVICE VARCHAR2 
    private String service;

    // DB : PROVINCE VARCHAR2 
    private String province;

    // DB : MAIN_CHARGE NUMBER 
    private BigDecimal mainCharge;

    // DB : GROUP_TYPE VARCHAR2 
    private String groupType;

    // DB : GROUP_CODE VARCHAR2 
    private String groupCode;

    // DB : NETWORK VARCHAR2 
    private String network;

    // DB : CODE_STATUS VARCHAR2 
    private String codeStatus;

    // DB : RANGE_INDEX NUMBER 
    private BigDecimal rangeIndex;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setIsdn( String isdn ) {
        this.isdn = isdn;
    }
    public String getIsdn() {
        return this.isdn;
    }

    public void setNoCode( BigDecimal noCode ) {
        this.noCode = noCode;
    }
    public BigDecimal getNoCode() {
        return this.noCode;
    }

    public void setDateActive( Date dateActive ) {
        this.dateActive = dateActive;
    }
    public Date getDateActive() {
        return this.dateActive;
    }

    public void setDateImport( Date dateImport ) {
        this.dateImport = dateImport;
    }
    public Date getDateImport() {
        return this.dateImport;
    }

    public void setSubtype( String subtype ) {
        this.subtype = subtype;
    }
    public String getSubtype() {
        return this.subtype;
    }

    public void setService( String service ) {
        this.service = service;
    }
    public String getService() {
        return this.service;
    }

    public void setProvince( String province ) {
        this.province = province;
    }
    public String getProvince() {
        return this.province;
    }

    public void setMainCharge( BigDecimal mainCharge ) {
        this.mainCharge = mainCharge;
    }
    public BigDecimal getMainCharge() {
        return this.mainCharge;
    }

    public void setGroupType( String groupType ) {
        this.groupType = groupType;
    }
    public String getGroupType() {
        return this.groupType;
    }

    public void setGroupCode( String groupCode ) {
        this.groupCode = groupCode;
    }
    public String getGroupCode() {
        return this.groupCode;
    }

    public void setNetwork( String network ) {
        this.network = network;
    }
    public String getNetwork() {
        return this.network;
    }

    public void setCodeStatus( String codeStatus ) {
        this.codeStatus = codeStatus;
    }
    public String getCodeStatus() {
        return this.codeStatus;
    }

    public void setRangeIndex( BigDecimal rangeIndex ) {
        this.rangeIndex = rangeIndex;
    }
    public BigDecimal getRangeIndex() {
        return this.rangeIndex;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(isdn);
        sb.append("|");
        sb.append(noCode);
        sb.append("|");
        sb.append(dateActive);
        sb.append("|");
        sb.append(dateImport);
        sb.append("|");
        sb.append(subtype);
        sb.append("|");
        sb.append(service);
        sb.append("|");
        sb.append(province);
        sb.append("|");
        sb.append(mainCharge);
        sb.append("|");
        sb.append(groupType);
        sb.append("|");
        sb.append(groupCode);
        sb.append("|");
        sb.append(network);
        sb.append("|");
        sb.append(codeStatus);
        sb.append("|");
        sb.append(rangeIndex);
        return sb.toString(); 
    } 


}
