/*
 * Created on 2 Jun 2016 ( Time 17:03:56 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package vnp.bean;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Java bean for 'IsdnCode' entity
 * 
 * @author Telosys Tools
 *
 */
public class IsdnCode implements Serializable {

	private static final long serialVersionUID = 1L;

	// ----------------------------------------------------------------------
	// ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
	// ----------------------------------------------------------------------
	// DB : ISDN VARCHAR2
	private String isdn;
	// DB : PROM_CODE NUMBER
	private long promCode;

	// ----------------------------------------------------------------------
	// ENTITY DATA FIELDS
	// ----------------------------------------------------------------------
	// DB : STATUS NUMBER
	private BigDecimal status;

	// DB : RANGE_INDEX NUMBER
	private BigDecimal rangeIndex;

	// ----------------------------------------------------------------------
	// GETTER & SETTER FOR THE KEY FIELD
	// ----------------------------------------------------------------------
	public void setIsdn(String isdn) {
		this.isdn = isdn;
	}

	public String getIsdn() {
		return this.isdn;
	}

	public void setPromCode(long promCode) {
		this.promCode = promCode;
	}

	public long getPromCode() {
		return this.promCode;
	}

	// ----------------------------------------------------------------------
	// GETTERS & SETTERS FOR FIELDS
	// ----------------------------------------------------------------------
	public void setStatus(BigDecimal status) {
		this.status = status;
	}

	public BigDecimal getStatus() {
		return this.status;
	}

	public void setRangeIndex(BigDecimal rangeIndex) {
		this.rangeIndex = rangeIndex;
	}

	public BigDecimal getRangeIndex() {
		return this.rangeIndex;
	}

	// ----------------------------------------------------------------------
	// toString METHOD
	// ----------------------------------------------------------------------
	public String toString() {
		StringBuffer sb = new StringBuffer();
		sb.append(isdn);
		sb.append("|");
		sb.append(promCode);
		sb.append("|");
		sb.append(status);
		sb.append("|");
		sb.append(rangeIndex);
		return sb.toString();
	}

}
