/*
 * Created on 20 Jul 2016 ( Time 23:23:24 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package vnp.bean;

import java.io.Serializable;

import java.util.Date;

/**
 * Java bean for 'Maduthuong' entity
 * 
 * @author Telosys Tools
 *
 */
public class Maduthuong implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // DB : ID NUMBER 
    private Long id;

    // DB : MSISDN VARCHAR2 
    private String msisdn;

    // DB : MDT NUMBER 
    private Long mdt;

    // DB : PROVINCE VARCHAR2 
    private String province;

    // DB : NOTE VARCHAR2 
    private String note;

    // DB : DATETIME DATE 
    private Date datetime;

    // DB : EVT_DTIME DATE 
    private Date evtDtime;

    // DB : STATUS NUMBER 
    private Long status;

    // DB : EVENTLOGS_SEQ_ID NUMBER 
    private Long eventlogsSeqId;

    // DB : SUBTYPE VARCHAR2 
    private String subtype;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setId( Long id ) {
        this.id = id;
    }
    public Long getId() {
        return this.id;
    }

    public void setMsisdn( String msisdn ) {
        this.msisdn = msisdn;
    }
    public String getMsisdn() {
        return this.msisdn;
    }

    public void setMdt( Long mdt ) {
        this.mdt = mdt;
    }
    public Long getMdt() {
        return this.mdt;
    }

    public void setProvince( String province ) {
        this.province = province;
    }
    public String getProvince() {
        return this.province;
    }

    public void setNote( String note ) {
        this.note = note;
    }
    public String getNote() {
        return this.note;
    }

    public void setDatetime( Date datetime ) {
        this.datetime = datetime;
    }
    public Date getDatetime() {
        return this.datetime;
    }

    public void setEvtDtime( Date evtDtime ) {
        this.evtDtime = evtDtime;
    }
    public Date getEvtDtime() {
        return this.evtDtime;
    }

    public void setStatus( Long status ) {
        this.status = status;
    }
    public Long getStatus() {
        return this.status;
    }

    public void setEventlogsSeqId( Long eventlogsSeqId ) {
        this.eventlogsSeqId = eventlogsSeqId;
    }
    public Long getEventlogsSeqId() {
        return this.eventlogsSeqId;
    }

    public void setSubtype( String subtype ) {
        this.subtype = subtype;
    }
    public String getSubtype() {
        return this.subtype;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(msisdn);
        sb.append("|");
        sb.append(mdt);
        sb.append("|");
        sb.append(province);
        sb.append("|");
        sb.append(note);
        sb.append("|");
        sb.append(datetime);
        sb.append("|");
        sb.append(evtDtime);
        sb.append("|");
        sb.append(status);
        sb.append("|");
        sb.append(eventlogsSeqId);
        sb.append("|");
        sb.append(subtype);
        return sb.toString(); 
    } 


}
