/*
 * Created on 17 Jun 2016 ( Time 12:37:08 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package vnp.bean;

import java.io.Serializable;

import java.util.Date;

/**
 * Java bean for 'PostpaidLog' entity
 * 
 * @author Telosys Tools
 *
 */
public class PostpaidLog implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // DB : ID NUMBER 
    private Long id;

    // DB : BILL_DATE DATE 
    private Date billDate;

    // DB : LOG_PROCESS DATE 
    private Date logProcess;

    // DB : STATUS VARCHAR2 
    private String status;

    // DB : NUM_REC NUMBER 
    private int numRec;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setId( Long id ) {
        this.id = id;
    }
    public Long getId() {
        return this.id;
    }

    public void setBillDate( Date billDate ) {
        this.billDate = billDate;
    }
    public Date getBillDate() {
        return this.billDate;
    }

    public void setLogProcess( Date logProcess ) {
        this.logProcess = logProcess;
    }
    public Date getLogProcess() {
        return this.logProcess;
    }

    public void setStatus( String status ) {
        this.status = status;
    }
    public String getStatus() {
        return this.status;
    }

    public void setNumRec( int numRec ) {
        this.numRec = numRec;
    }
    public int getNumRec() {
        return this.numRec;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(billDate);
        sb.append("|");
        sb.append(logProcess);
        sb.append("|");
        sb.append(status);
        sb.append("|");
        sb.append(numRec);
        return sb.toString(); 
    } 


}
