/*
 * Created on 7 Jun 2016 ( Time 13:19:54 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package vnp.bean;

import java.io.Serializable;

import java.util.Date;

/**
 * Java bean for 'PrizeRewardLog' entity
 * 
 * @author Telosys Tools
 *
 */
public class PrizeRewardLog implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // DB : MSISDN VARCHAR2 
    private String msisdn;

    // DB : PRIZE_ID NUMBER 
    private int prizeId;

    // DB : SUBTYPE VARCHAR2 
    private String subtype;

    // DB : ACTIONLOG VARCHAR2 
    private String actionlog;

    // DB : RESULTLOG VARCHAR2 
    private String resultlog;

    // DB : DATE_TIME DATE 
    private Date dateTime;

    // DB : STATUS NUMBER 
    private int status;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setMsisdn( String msisdn ) {
        this.msisdn = msisdn;
    }
    public String getMsisdn() {
        return this.msisdn;
    }

    public void setPrizeId( int prizeId ) {
        this.prizeId = prizeId;
    }
    public int getPrizeId() {
        return this.prizeId;
    }

    public void setSubtype( String subtype ) {
        this.subtype = subtype;
    }
    public String getSubtype() {
        return this.subtype;
    }

    public void setActionlog( String actionlog ) {
        this.actionlog = actionlog;
    }
    public String getActionlog() {
        return this.actionlog;
    }

    public void setResultlog( String resultlog ) {
        this.resultlog = resultlog;
    }
    public String getResultlog() {
        return this.resultlog;
    }

    public void setDateTime( Date dateTime ) {
        this.dateTime = dateTime;
    }
    public Date getDateTime() {
        return this.dateTime;
    }

    public void setStatus( int status ) {
        this.status = status;
    }
    public int getStatus() {
        return this.status;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(msisdn);
        sb.append("|");
        sb.append(prizeId);
        sb.append("|");
        sb.append(subtype);
        sb.append("|");
        sb.append(actionlog);
        sb.append("|");
        sb.append(resultlog);
        sb.append("|");
        sb.append(dateTime);
        sb.append("|");
        sb.append(status);
        return sb.toString(); 
    } 


}
