/*
 * Created on 29 Jul 2016 ( Time 09:20:28 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package vnp.bean;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Java bean for 'PrizeList' entity
 * 
 * @author Telosys Tools
 *
 */
public class PrizeList implements Serializable {

	private static final long serialVersionUID = 1L;

	// ----------------------------------------------------------------------
	// ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
	// ----------------------------------------------------------------------
	// DB : ID NUMBER
	private Long id;

	// ----------------------------------------------------------------------
	// ENTITY DATA FIELDS
	// ----------------------------------------------------------------------
	// DB : PRIZE_LEVEL NUMBER
	private int prizeLevel;

	// DB : PRIZE_NAME VARCHAR2
	private String prizeName;

	// DB : PRIZE_DESCRIPTION VARCHAR2
	private String prizeDescription;

	// DB : PRIZE_PRICE NUMBER
	private BigDecimal prizePrice;

	// DB : PRIZE_TOTAL NUMBER
	private int prizeTotal;

	// DB : CAMPAIGN_ID NUMBER
	private Long campaignId;

	private int autoPayment;
	private int prizeDays;

	public int getPrizeDays() {
		return prizeDays;
	}

	public void setPrizeDays(int prizeDays) {
		this.prizeDays = prizeDays;
	}

	public int getAutoPayment() {
		return autoPayment;
	}

	public void setAutoPayment(int autoPayment) {
		this.autoPayment = autoPayment;
	}

	// ----------------------------------------------------------------------
	// GETTER & SETTER FOR THE KEY FIELD
	// ----------------------------------------------------------------------
	public void setId(Long id) {
		this.id = id;
	}

	public Long getId() {
		return this.id;
	}

	// ----------------------------------------------------------------------
	// GETTERS & SETTERS FOR FIELDS
	// ----------------------------------------------------------------------
	public void setPrizeLevel(int prizeLevel) {
		this.prizeLevel = prizeLevel;
	}

	public int getPrizeLevel() {
		return this.prizeLevel;
	}

	public void setPrizeName(String prizeName) {
		this.prizeName = prizeName;
	}

	public String getPrizeName() {
		return this.prizeName;
	}

	public void setPrizeDescription(String prizeDescription) {
		this.prizeDescription = prizeDescription;
	}

	public String getPrizeDescription() {
		return this.prizeDescription;
	}

	public void setPrizePrice(BigDecimal prizePrice) {
		this.prizePrice = prizePrice;
	}

	public BigDecimal getPrizePrice() {
		return this.prizePrice;
	}

	public void setPrizeTotal(int prizeTotal) {
		this.prizeTotal = prizeTotal;
	}

	public int getPrizeTotal() {
		return this.prizeTotal;
	}

	public void setCampaignId(Long campaignId) {
		this.campaignId = campaignId;
	}

	public Long getCampaignId() {
		return this.campaignId;
	}

	// ----------------------------------------------------------------------
	// toString METHOD
	// ----------------------------------------------------------------------
	public String toString() {
		StringBuffer sb = new StringBuffer();
		sb.append(id);
		sb.append("|");
		sb.append(prizeLevel);
		sb.append("|");
		sb.append(prizeName);
		sb.append("|");
		sb.append(prizeDescription);
		sb.append("|");
		sb.append(prizePrice);
		sb.append("|");
		sb.append(prizeTotal);
		sb.append("|");
		sb.append(campaignId);
		sb.append("|");
		sb.append(autoPayment);
		sb.append("|");
		sb.append(prizeDays);
		return sb.toString();
	}

}
