/*
 * Created on 7 Jun 2016 ( Time 10:15:42 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package vnp.bean;

import java.io.Serializable;
import java.util.Date;

/**
 * Java bean for 'PrizeReward' entity
 * 
 * @author Telosys Tools
 *
 */
public class PrizeReward implements Serializable {

	private static final long serialVersionUID = 1L;

	// ----------------------------------------------------------------------
	// ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
	// ----------------------------------------------------------------------

	// ----------------------------------------------------------------------
	// ENTITY DATA FIELDS
	// ----------------------------------------------------------------------
	// DB : MSISDN VARCHAR2
	private String msisdn;

	// DB : PRIZE_ID NUMBER
	private int prizeId;

	// DB : PRIZE_NAME VARCHAR2
	private String prizeName;

	// DB : REWARD_DATE DATE
	private Date rewardDate;

	// DB : STATUS NUMBER
	private int status;

	// DB : SUBTYPE VARCHAR2
	private String subtype;

	// DB : REWARD_CODE NUMBER
	private Long rewardCode;

	private int campaign_id;
	private int autoPayment;
	private long rewardPrice;
	// ----------------------------------------------------------------------
	// GETTER & SETTER FOR THE KEY FIELD
	// ----------------------------------------------------------------------

	public int getAutoPayment() {
		return autoPayment;
	}

	public void setAutoPayment(int autoPayment) {
		this.autoPayment = autoPayment;
	}

	public long getRewardPrice() {
		return rewardPrice;
	}

	public void setRewardPrice(long rewardPrice) {
		this.rewardPrice = rewardPrice;
	}

	public int getCampaign_id() {
		return campaign_id;
	}

	public void setCampaign_id(int campaign_id) {
		this.campaign_id = campaign_id;
	}

	// ----------------------------------------------------------------------
	// GETTERS & SETTERS FOR FIELDS
	// ----------------------------------------------------------------------
	public void setMsisdn(String msisdn) {
		this.msisdn = msisdn;
	}

	public String getMsisdn() {
		return this.msisdn;
	}

	public void setPrizeId(int prizeId) {
		this.prizeId = prizeId;
	}

	public int getPrizeId() {
		return this.prizeId;
	}

	public void setPrizeName(String prizeName) {
		this.prizeName = prizeName;
	}

	public String getPrizeName() {
		return this.prizeName;
	}

	public void setRewardDate(Date rewardDate) {
		this.rewardDate = rewardDate;
	}

	public Date getRewardDate() {
		return this.rewardDate;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public int getStatus() {
		return this.status;
	}

	public void setSubtype(String subtype) {
		this.subtype = subtype;
	}

	public String getSubtype() {
		return this.subtype;
	}

	public void setRewardCode(Long rewardCode) {
		this.rewardCode = rewardCode;
	}

	public Long getRewardCode() {
		return this.rewardCode;
	}

	// ----------------------------------------------------------------------
	// toString METHOD
	// ----------------------------------------------------------------------
	public String toString() {
		StringBuffer sb = new StringBuffer();
		sb.append(msisdn);
		sb.append("|");
		sb.append(prizeId);
		sb.append("|");
		sb.append(prizeName);
		sb.append("|");
		sb.append(rewardDate);
		sb.append("|");
		sb.append(status);
		sb.append("|");
		sb.append(subtype);
		sb.append("|");
		sb.append(rewardCode);
		return sb.toString();
	}

}
