/*
 * Created on 23 Jun 2016 ( Time 14:40:50 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package vnp.bean;

import java.io.Serializable;
import java.util.Date;

/**
 * Java bean for 'PrizeRewardBuffer' entity
 * 
 * @author Telosys Tools
 *
 */
public class PrizeRewardBuffer implements Serializable {

	private static final long serialVersionUID = 1L;

	// ----------------------------------------------------------------------
	// ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
	// ----------------------------------------------------------------------

	// ----------------------------------------------------------------------
	// ENTITY DATA FIELDS
	// ----------------------------------------------------------------------
	// DB : MSISDN VARCHAR2
	private String msisdn;

	// DB : REWARD_CODE NUMBER
	private Long rewardCode;

	// DB : PRIZE_LEVEL NUMBER
	private int prizeLevel;

	// DB : PRIZE_DATE DATE
	private Date prizeDate;

	// DB : STATUS NUMBER
	private int status;
	private int campaign_id;

	// ----------------------------------------------------------------------
	// GETTER & SETTER FOR THE KEY FIELD
	// ----------------------------------------------------------------------

	public int getCampaign_id() {
		return campaign_id;
	}

	public void setCampaign_id(int campaign_id) {
		this.campaign_id = campaign_id;
	}

	// ----------------------------------------------------------------------
	// GETTERS & SETTERS FOR FIELDS
	// ----------------------------------------------------------------------
	public void setMsisdn(String msisdn) {
		this.msisdn = msisdn;
	}

	public String getMsisdn() {
		return this.msisdn;
	}

	public void setRewardCode(Long rewardCode) {
		this.rewardCode = rewardCode;
	}

	public Long getRewardCode() {
		return this.rewardCode;
	}

	public void setPrizeLevel(int prizeLevel) {
		this.prizeLevel = prizeLevel;
	}

	public int getPrizeLevel() {
		return this.prizeLevel;
	}

	public void setPrizeDate(Date prizeDate) {
		this.prizeDate = prizeDate;
	}

	public Date getPrizeDate() {
		return this.prizeDate;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public int getStatus() {
		return this.status;
	}

	// ----------------------------------------------------------------------
	// toString METHOD
	// ----------------------------------------------------------------------
	public String toString() {
		StringBuffer sb = new StringBuffer();
		sb.append(msisdn);
		sb.append("|");
		sb.append(rewardCode);
		sb.append("|");
		sb.append(prizeLevel);
		sb.append("|");
		sb.append(prizeDate);
		sb.append("|");
		sb.append(status);
		return sb.toString();
	}

}
