/*
 * Created on 2 Jun 2016 ( Time 17:01:54 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package vnp.bean;

import java.io.Serializable;

import java.util.Date;

/**
 * Java bean for 'QueuePrepaidBroadcast' entity
 * 
 * @author Telosys Tools
 *
 */
public class QueuePrepaidBroadcast implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // DB : MSISDN VARCHAR2 
    private String msisdn;

    // DB : DATE_TIME DATE 
    private Date dateTime;

    // DB : SMS_CONTENT VARCHAR2 
    private String smsContent;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setMsisdn( String msisdn ) {
        this.msisdn = msisdn;
    }
    public String getMsisdn() {
        return this.msisdn;
    }

    public void setDateTime( Date dateTime ) {
        this.dateTime = dateTime;
    }
    public Date getDateTime() {
        return this.dateTime;
    }

    public void setSmsContent( String smsContent ) {
        this.smsContent = smsContent;
    }
    public String getSmsContent() {
        return this.smsContent;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(msisdn);
        sb.append("|");
        sb.append(dateTime);
        sb.append("|");
        sb.append(smsContent);
        return sb.toString(); 
    } 


}
