/*
 * Created on 2 Jun 2016 ( Time 17:03:04 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package vnp.bean;

import java.io.Serializable;

import java.math.BigDecimal;
import java.util.Date;

/**
 * Java bean for 'SmsLog' entity
 * 
 * @author Telosys Tools
 *
 */
public class SmsLog implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // DB : ID NUMBER 
    private BigDecimal id;

    // DB : MSISDN VARCHAR2 
    private String msisdn;

    // DB : RECEIVER_TIME DATE 
    private Date receiverTime;

    // DB : SMS_CONTENT VARCHAR2 
    private String smsContent;

    // DB : STATUS NUMBER 
    private BigDecimal status;

    // DB : RESPONSE_CONTENT VARCHAR2 
    private String responseContent;

    // DB : RESPONSE_TIME DATE 
    private Date responseTime;

    // DB : NOTE VARCHAR2 
    private String note;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setId( BigDecimal id ) {
        this.id = id;
    }
    public BigDecimal getId() {
        return this.id;
    }

    public void setMsisdn( String msisdn ) {
        this.msisdn = msisdn;
    }
    public String getMsisdn() {
        return this.msisdn;
    }

    public void setReceiverTime( Date receiverTime ) {
        this.receiverTime = receiverTime;
    }
    public Date getReceiverTime() {
        return this.receiverTime;
    }

    public void setSmsContent( String smsContent ) {
        this.smsContent = smsContent;
    }
    public String getSmsContent() {
        return this.smsContent;
    }

    public void setStatus( BigDecimal status ) {
        this.status = status;
    }
    public BigDecimal getStatus() {
        return this.status;
    }

    public void setResponseContent( String responseContent ) {
        this.responseContent = responseContent;
    }
    public String getResponseContent() {
        return this.responseContent;
    }

    public void setResponseTime( Date responseTime ) {
        this.responseTime = responseTime;
    }
    public Date getResponseTime() {
        return this.responseTime;
    }

    public void setNote( String note ) {
        this.note = note;
    }
    public String getNote() {
        return this.note;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(msisdn);
        sb.append("|");
        sb.append(receiverTime);
        sb.append("|");
        sb.append(smsContent);
        sb.append("|");
        sb.append(status);
        sb.append("|");
        sb.append(responseContent);
        sb.append("|");
        sb.append(responseTime);
        sb.append("|");
        sb.append(note);
        return sb.toString(); 
    } 


}
