/*
 * Created on 3 Jun 2016 ( Time 16:24:32 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package vnp.bean;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Java bean for 'SmsMo' entity
 * 
 * @author Telosys Tools
 *
 */
public class SmsMo implements Serializable {

	private static final long serialVersionUID = 1L;

	// ----------------------------------------------------------------------
	// ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
	// ----------------------------------------------------------------------
	// DB : ID NUMBER
	private long id;

	// ----------------------------------------------------------------------
	// ENTITY DATA FIELDS
	// ----------------------------------------------------------------------
	// DB : MSISDN VARCHAR2
	private String msisdn;

	// DB : RECEIVE_TIME DATE
	private Date receiveTime;

	// DB : SMS_CONTENT VARCHAR2
	private String smsContent;

	// DB : RESPONSE_TIME VARCHAR2
	private String responseTime;

	// DB : RESPONSE_ID NUMBER
	private BigDecimal responseId;

	// DB : STATUS NUMBER
	private BigDecimal status;

	// ----------------------------------------------------------------------
	// GETTER & SETTER FOR THE KEY FIELD
	// ----------------------------------------------------------------------
	public void setId(long id) {
		this.id = id;
	}

	public long getId() {
		return this.id;
	}

	// ----------------------------------------------------------------------
	// GETTERS & SETTERS FOR FIELDS
	// ----------------------------------------------------------------------
	public void setMsisdn(String msisdn) {
		this.msisdn = msisdn;
	}

	public String getMsisdn() {
		return this.msisdn;
	}

	public void setReceiveTime(Date receiveTime) {
		this.receiveTime = receiveTime;
	}

	public Date getReceiveTime() {
		return this.receiveTime;
	}

	public void setSmsContent(String smsContent) {
		this.smsContent = smsContent;
	}

	public String getSmsContent() {
		return this.smsContent;
	}

	public void setResponseTime(String responseTime) {
		this.responseTime = responseTime;
	}

	public String getResponseTime() {
		return this.responseTime;
	}

	public void setResponseId(BigDecimal responseId) {
		this.responseId = responseId;
	}

	public BigDecimal getResponseId() {
		return this.responseId;
	}

	public void setStatus(BigDecimal status) {
		this.status = status;
	}

	public BigDecimal getStatus() {
		return this.status;
	}

	// ----------------------------------------------------------------------
	// toString METHOD
	// ----------------------------------------------------------------------
	public String toString() {
		StringBuffer sb = new StringBuffer();
		sb.append(id);
		sb.append("|");
		sb.append(msisdn);
		sb.append("|");
		sb.append(receiveTime);
		sb.append("|");
		sb.append(smsContent);
		sb.append("|");
		sb.append(responseTime);
		sb.append("|");
		sb.append(responseId);
		sb.append("|");
		sb.append(status);
		return sb.toString();
	}

}
