/*
 * Created on 3 Jun 2016 ( Time 16:24:32 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package vnp.bean;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Java bean for 'SmsMt' entity
 * 
 * @author Telosys Tools
 *
 */
public class SmsMt implements Serializable {

	private static final long serialVersionUID = 1L;

	// ----------------------------------------------------------------------
	// ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
	// ----------------------------------------------------------------------
	// DB : ID NUMBER
	private BigDecimal id;
	private String shortCode;

	public String getShortCode() {
		return shortCode;
	}

	public void setShortCode(String shortCode) {
		this.shortCode = shortCode;
	}

	// ----------------------------------------------------------------------
	// ENTITY DATA FIELDS
	// ----------------------------------------------------------------------
	// DB : MSISDN VARCHAR2
	private String msisdn;

	// DB : SUBMIT_TIME DATE
	private Date submitTime;

	// DB : SMS_CONTENT VARCHAR2
	private String smsContent;

	// DB : MO_ID NUMBER
	private long moId;

	// DB : STATUS NUMBER
	private BigDecimal status;

	// DB : SENT_TIME DATE
	private Date sentTime;

	// ----------------------------------------------------------------------
	// GETTER & SETTER FOR THE KEY FIELD
	// ----------------------------------------------------------------------
	public void setId(BigDecimal id) {
		this.id = id;
	}

	public BigDecimal getId() {
		return this.id;
	}

	// ----------------------------------------------------------------------
	// GETTERS & SETTERS FOR FIELDS
	// ----------------------------------------------------------------------
	public void setMsisdn(String msisdn) {
		this.msisdn = msisdn;
	}

	public String getMsisdn() {
		return this.msisdn;
	}

	public void setSubmitTime(Date submitTime) {
		this.submitTime = submitTime;
	}

	public Date getSubmitTime() {
		return this.submitTime;
	}

	public void setSmsContent(String smsContent) {
		this.smsContent = smsContent;
	}

	public String getSmsContent() {
		return this.smsContent;
	}

	public void setMoId(long moId) {
		this.moId = moId;
	}

	public long getMoId() {
		return this.moId;
	}

	public void setStatus(BigDecimal status) {
		this.status = status;
	}

	public BigDecimal getStatus() {
		return this.status;
	}

	public void setSentTime(Date sentTime) {
		this.sentTime = sentTime;
	}

	public Date getSentTime() {
		return this.sentTime;
	}

	// ----------------------------------------------------------------------
	// toString METHOD
	// ----------------------------------------------------------------------
	public String toString() {
		StringBuffer sb = new StringBuffer();
		sb.append(id);
		sb.append("|");
		sb.append(msisdn);
		sb.append("|");
		sb.append(submitTime);
		sb.append("|");
		sb.append(smsContent);
		sb.append("|");
		sb.append(moId);
		sb.append("|");
		sb.append(status);
		sb.append("|");
		sb.append(sentTime);
		return sb.toString();
	}

}
