/*
 * Created on 17 Jun 2016 ( Time 12:35:41 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package vnp.bean;

import java.io.Serializable;

import java.math.BigDecimal;
import java.util.Date;

/**
 * Java bean for 'SubPostAccumulate' entity
 * 
 * @author Telosys Tools
 *
 */
public class SubPostAccumulate implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // DB : MSISDN VARCHAR2 
    private String msisdn;

    // DB : ACC_VALUE NUMBER 
    private BigDecimal accValue;

    // DB : LAST_ACC_VALUE NUMBER 
    private BigDecimal lastAccValue;

    // DB : CODE_COUNT NUMBER 
    private int codeCount;

    // DB : LAST_CODE_COUNT NUMBER 
    private int lastCodeCount;

    // DB : DATE_TIME DATE 
    private Date dateTime;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setMsisdn( String msisdn ) {
        this.msisdn = msisdn;
    }
    public String getMsisdn() {
        return this.msisdn;
    }

    public void setAccValue( BigDecimal accValue ) {
        this.accValue = accValue;
    }
    public BigDecimal getAccValue() {
        return this.accValue;
    }

    public void setLastAccValue( BigDecimal lastAccValue ) {
        this.lastAccValue = lastAccValue;
    }
    public BigDecimal getLastAccValue() {
        return this.lastAccValue;
    }

    public void setCodeCount( int codeCount ) {
        this.codeCount = codeCount;
    }
    public int getCodeCount() {
        return this.codeCount;
    }

    public void setLastCodeCount( int lastCodeCount ) {
        this.lastCodeCount = lastCodeCount;
    }
    public int getLastCodeCount() {
        return this.lastCodeCount;
    }

    public void setDateTime( Date dateTime ) {
        this.dateTime = dateTime;
    }
    public Date getDateTime() {
        return this.dateTime;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(msisdn);
        sb.append("|");
        sb.append(accValue);
        sb.append("|");
        sb.append(lastAccValue);
        sb.append("|");
        sb.append(codeCount);
        sb.append("|");
        sb.append(lastCodeCount);
        sb.append("|");
        sb.append(dateTime);
        return sb.toString(); 
    } 


}
