/*
 * Created on 17 Jun 2016 ( Time 12:35:41 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package vnp.bean;

import java.io.Serializable;

import java.math.BigDecimal;
import java.util.Date;

/**
 * Java bean for 'SubsInDaily' entity
 * 
 * @author Telosys Tools
 *
 */
public class SubsInDaily implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // DB : SUBSCRIBER_ID VARCHAR2 
    private String subscriberId;

    // DB : TOTAL_TKC NUMBER 
    private BigDecimal totalTkc;

    // DB : DATE_TIME DATE 
    private Date dateTime;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setSubscriberId( String subscriberId ) {
        this.subscriberId = subscriberId;
    }
    public String getSubscriberId() {
        return this.subscriberId;
    }

    public void setTotalTkc( BigDecimal totalTkc ) {
        this.totalTkc = totalTkc;
    }
    public BigDecimal getTotalTkc() {
        return this.totalTkc;
    }

    public void setDateTime( Date dateTime ) {
        this.dateTime = dateTime;
    }
    public Date getDateTime() {
        return this.dateTime;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(subscriberId);
        sb.append("|");
        sb.append(totalTkc);
        sb.append("|");
        sb.append(dateTime);
        return sb.toString(); 
    } 


}
