/*
 * Created on 17 Jun 2016 ( Time 12:35:41 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package vnp.bean;

import java.io.Serializable;

import java.util.Date;

/**
 * Java bean for 'SubsInLogs' entity
 * 
 * @author Telosys Tools
 *
 */
public class SubsInLogs implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // DB : DATE_TIME DATE 
    private Date dateTime;

    // DB : STATUS NUMBER 
    private int status;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setDateTime( Date dateTime ) {
        this.dateTime = dateTime;
    }
    public Date getDateTime() {
        return this.dateTime;
    }

    public void setStatus( int status ) {
        this.status = status;
    }
    public int getStatus() {
        return this.status;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(dateTime);
        sb.append("|");
        sb.append(status);
        return sb.toString(); 
    } 


}
