/*
 * Created on 18 Nov 2016 ( Time 09:26:51 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package vnp.bean;

import java.io.Serializable;


/**
 * Java bean for 'WinConfig' entity
 * 
 * @author Telosys Tools
 *
 */
public class WinConfig implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    // DB : CAMPAIGN_ID NUMBER 
    private Long campaignId;
    // DB : CONFIG_KEY NVARCHAR2 
    private String configKey;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // DB : CONFIG_VALUE NVARCHAR2 
    private String configValue;

    // DB : CONFIG_TYPE NVARCHAR2 
    private String configType;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setCampaignId( Long campaignId ) {
        this.campaignId = campaignId ;
    }

    public Long getCampaignId() {
        return this.campaignId;
    }

    public void setConfigKey( String configKey ) {
        this.configKey = configKey ;
    }

    public String getConfigKey() {
        return this.configKey;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setConfigValue( String configValue ) {
        this.configValue = configValue;
    }
    public String getConfigValue() {
        return this.configValue;
    }

    public void setConfigType( String configType ) {
        this.configType = configType;
    }
    public String getConfigType() {
        return this.configType;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(campaignId);
        sb.append("|");
        sb.append(configKey);
        sb.append("|");
        sb.append(configValue);
        sb.append("|");
        sb.append(configType);
        return sb.toString(); 
    } 


}
