/*
 * Created on 18 Nov 2016 ( Time 09:26:51 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package vnp.bean;

import java.io.Serializable;

import java.util.Date;

/**
 * Java bean for 'WinCampaign' entity
 * 
 * @author Telosys Tools
 *
 */
public class WinCampaign implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    // DB : CAMPAIGN_ID NUMBER 
    private Long campaignId;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // DB : SERVICE_ID NUMBER 
    private Long serviceId;

    // DB : CAMPAIGN_NAME VARCHAR2 
    private String campaignName;

    // DB : START_TIME DATE 
    private Date startTime;

    // DB : FINISH_TIME DATE 
    private Date finishTime;

    // DB : NOTES VARCHAR2 
    private String notes;

    // DB : ACTIVE NUMBER 
    private Integer active;

    // DB : TYPE VARCHAR2 
    private String type;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setCampaignId( Long campaignId ) {
        this.campaignId = campaignId ;
    }

    public Long getCampaignId() {
        return this.campaignId;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setServiceId( Long serviceId ) {
        this.serviceId = serviceId;
    }
    public Long getServiceId() {
        return this.serviceId;
    }

    public void setCampaignName( String campaignName ) {
        this.campaignName = campaignName;
    }
    public String getCampaignName() {
        return this.campaignName;
    }

    public void setStartTime( Date startTime ) {
        this.startTime = startTime;
    }
    public Date getStartTime() {
        return this.startTime;
    }

    public void setFinishTime( Date finishTime ) {
        this.finishTime = finishTime;
    }
    public Date getFinishTime() {
        return this.finishTime;
    }

    public void setNotes( String notes ) {
        this.notes = notes;
    }
    public String getNotes() {
        return this.notes;
    }

    public void setActive( Integer active ) {
        this.active = active;
    }
    public Integer getActive() {
        return this.active;
    }

    public void setType( String type ) {
        this.type = type;
    }
    public String getType() {
        return this.type;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(serviceId);
        sb.append("|");
        sb.append(campaignId);
        sb.append("|");
        sb.append(campaignName);
        sb.append("|");
        sb.append(startTime);
        sb.append("|");
        sb.append(finishTime);
        sb.append("|");
        sb.append(notes);
        sb.append("|");
        sb.append(active);
        sb.append("|");
        sb.append(type);
        return sb.toString(); 
    } 


}
