/*
 * Created on 18 Nov 2016 ( Time 09:26:51 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package vnp.bean;

import java.io.Serializable;

import java.util.Date;

/**
 * Java bean for 'WinMtLog' entity
 * 
 * @author Telosys Tools
 *
 */
public class WinMtLog implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // DB : CAMPAIGN_ID NUMBER 
    private Long campaignId;

    // DB : MSISDN NVARCHAR2 
    private String msisdn;

    // DB : MT_CONTENT NVARCHAR2 
    private String mtContent;

    // DB : STATUS NUMBER 
    private Integer status;

    // DB : SENT_TIME DATE 
    private Date sentTime;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setCampaignId( Long campaignId ) {
        this.campaignId = campaignId;
    }
    public Long getCampaignId() {
        return this.campaignId;
    }

    public void setMsisdn( String msisdn ) {
        this.msisdn = msisdn;
    }
    public String getMsisdn() {
        return this.msisdn;
    }

    public void setMtContent( String mtContent ) {
        this.mtContent = mtContent;
    }
    public String getMtContent() {
        return this.mtContent;
    }

    public void setStatus( Integer status ) {
        this.status = status;
    }
    public Integer getStatus() {
        return this.status;
    }

    public void setSentTime( Date sentTime ) {
        this.sentTime = sentTime;
    }
    public Date getSentTime() {
        return this.sentTime;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(campaignId);
        sb.append("|");
        sb.append(msisdn);
        sb.append("|");
        sb.append(mtContent);
        sb.append("|");
        sb.append(status);
        sb.append("|");
        sb.append(sentTime);
        return sb.toString(); 
    } 


}
