/*
 * Created on 18 Nov 2016 ( Time 09:26:51 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package vnp.bean;

import java.io.Serializable;


/**
 * Java bean for 'WinMtTemplate' entity
 * 
 * @author Telosys Tools
 *
 */
public class WinMtTemplate implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    // DB : CAMPAIGN_ID NUMBER 
    private Long campaignId;
    // DB : MT_CODE NVARCHAR2 
    private String mtCode;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // DB : MT_CONTENT NVARCHAR2 
    private String mtContent;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setCampaignId( Long campaignId ) {
        this.campaignId = campaignId ;
    }

    public Long getCampaignId() {
        return this.campaignId;
    }

    public void setMtCode( String mtCode ) {
        this.mtCode = mtCode ;
    }

    public String getMtCode() {
        return this.mtCode;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setMtContent( String mtContent ) {
        this.mtContent = mtContent;
    }
    public String getMtContent() {
        return this.mtContent;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(campaignId);
        sb.append("|");
        sb.append(mtCode);
        sb.append("|");
        sb.append(mtContent);
        return sb.toString(); 
    } 


}
