/*
 * Created on 18 Nov 2016 ( Time 09:26:51 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package vnp.bean;

import java.io.Serializable;

import java.math.BigDecimal;

/**
 * Java bean for 'WinPrizes' entity
 * 
 * @author Telosys Tools
 *
 */
public class WinPrizes implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    // DB : CAMPAIGN_ID NUMBER 
    private Long campaignId;
    // DB : PRIZE_LEVEL NUMBER 
    private Long prizeLevel;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // DB : PRIZE_NAME NVARCHAR2 
    private String prizeName;

    // DB : PRIZE_DESCRIPTION NVARCHAR2 
    private String prizeDescription;

    // DB : PRIZE_PRICE NUMBER 
    private BigDecimal prizePrice;

    // DB : PRIZE_TOTAL NUMBER 
    private Integer prizeTotal;

    // DB : AUTOPAYMENT NUMBER 
    private Integer autopayment;

    // DB : PRIZE_DAYS NUMBER 
    private Integer prizeDays;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setCampaignId( Long campaignId ) {
        this.campaignId = campaignId ;
    }

    public Long getCampaignId() {
        return this.campaignId;
    }

    public void setPrizeLevel( Long prizeLevel ) {
        this.prizeLevel = prizeLevel ;
    }

    public Long getPrizeLevel() {
        return this.prizeLevel;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setPrizeName( String prizeName ) {
        this.prizeName = prizeName;
    }
    public String getPrizeName() {
        return this.prizeName;
    }

    public void setPrizeDescription( String prizeDescription ) {
        this.prizeDescription = prizeDescription;
    }
    public String getPrizeDescription() {
        return this.prizeDescription;
    }

    public void setPrizePrice( BigDecimal prizePrice ) {
        this.prizePrice = prizePrice;
    }
    public BigDecimal getPrizePrice() {
        return this.prizePrice;
    }

    public void setPrizeTotal( Integer prizeTotal ) {
        this.prizeTotal = prizeTotal;
    }
    public Integer getPrizeTotal() {
        return this.prizeTotal;
    }

    public void setAutopayment( Integer autopayment ) {
        this.autopayment = autopayment;
    }
    public Integer getAutopayment() {
        return this.autopayment;
    }

    public void setPrizeDays( Integer prizeDays ) {
        this.prizeDays = prizeDays;
    }
    public Integer getPrizeDays() {
        return this.prizeDays;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(campaignId);
        sb.append("|");
        sb.append(prizeLevel);
        sb.append("|");
        sb.append(prizeName);
        sb.append("|");
        sb.append(prizeDescription);
        sb.append("|");
        sb.append(prizePrice);
        sb.append("|");
        sb.append(prizeTotal);
        sb.append("|");
        sb.append(autopayment);
        sb.append("|");
        sb.append(prizeDays);
        return sb.toString(); 
    } 


}
