# Set root logger level to DEBUG and its only appender to A1.
log4j.rootLogger=ALL, A1
log4j.category.org.apache.axis=ERROR,OFF
log4j.category.org.apache.sshd.server=ERROR,OFF
log4j.category.org.mortbay.log=ERROR,OFF

# A1 is set to be a ConsoleAppender.
log4j.appender.A1=org.apache.log4j.RollingFileAppender
log4j.appender.A1.File=log/general/info.log
log4j.appender.A1.MaxFileSize=1000KB
log4j.appender.A1.MaxBackupIndex=10

# OFF is set to be a ConsoleAppender.
log4j.appender.OFF=org.apache.log4j.RollingFileAppender
log4j.appender.OFF.File=log/general/info2.log
log4j.appender.OFF.MaxFileSize=1000KB
log4j.appender.OFF.MaxBackupIndex=-1

# A1 uses PatternLayout.
log4j.appender.A1.layout=org.apache.log4j.PatternLayout
log4j.appender.A1.layout.ConversionPattern=%-10r [%t] %-5p %c %x - %m%n

# OFF uses PatternLayout.
log4j.appender.OFF.layout=org.apache.log4j.PatternLayout
log4j.appender.OFF.layout.ConversionPattern=%-10r [%t] %-5p %c %x - %m%n
